// @/components/adLibrary/archive/AdArchive.tsx
"use client";

import { useCallback, useRef, useState } from "react";
import { fetchAdArchive, FetchAdsParams } from "@/actions/adController";
import { AD_ARCHIVE_FILTERS } from "@/configuration/globalFilters";
import { Database, Search } from "lucide-react";
import { toast } from "sonner";

import { AdData } from "@/types/ad";
import SearchFilters from "@/components/adTool/search/SearchFilters";
import { ScrollButtons } from "@/components/adTool/sharedComponents/ScrollButtons";
import SearchResults from "@/components/adTool/sharedComponents/SearchResults";
import TitleSection from "@/components/adTool/sharedComponents/TitleSection";

export default function AdArchive() {
  const [ads, setAds] = useState<AdData[] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [totalCount, setTotalCount] = useState<number | null>(null);
  const [fetchedCount, setFetchedCount] = useState<number>(0);
  const [hasNextPage, setHasNextPage] = useState<boolean>(false);

  // Tracks the explicit parameters generated by the form submission
  const lastParamsRef = useRef<URLSearchParams | null>(null);
  const currentPageRef = useRef<number>(1);

  const executeSearch = useCallback(
    async (params: URLSearchParams, isLoadMore = false) => {
      setIsLoading(true);
      setError(null);
      lastParamsRef.current = params; // Save params for "Load More"

      try {
        const pageToFetch = isLoadMore ? currentPageRef.current + 1 : 1;

        const fetchParams: FetchAdsParams = {
          page: pageToFetch,
          limit: 20,
          search: params.get("search") || undefined,
          pageName: params.get("pageName") || undefined,
          domain: params.get("domain") || undefined,
          pageCategory: params.get("pageCategory") || undefined,
          countries: params.getAll("countries"),
          platforms: params.getAll("platforms"),
          displayFormats: params.getAll("displayFormats"),
          ctaTypes: params.getAll("ctaTypes"),
          minCollation: params.get("collationCountMin")
            ? Number(params.get("collationCountMin"))
            : undefined,
          maxCollation: params.get("collationCountMax")
            ? Number(params.get("collationCountMax"))
            : undefined,
          startDateMin: params.get("startDateMin") || undefined,
          startDateMax: params.get("startDateMax") || undefined,
        };

        const result = await fetchAdArchive(fetchParams);

        if (result.error) {
          toast.error(result.error);
          throw new Error(result.error);
        }

        if (result.ads && result.pagination) {
          const extractedAds = result.ads.map((ad) => ad.adData);

          if (isLoadMore) {
            setAds((prev) => [...(prev || []), ...extractedAds]);
            setFetchedCount((prev) => prev + extractedAds.length);
          } else {
            setAds(extractedAds);
            setTotalCount(result.pagination.total);
            setFetchedCount(extractedAds.length);
          }

          currentPageRef.current = result.pagination.current;
          setHasNextPage(result.pagination.current < result.pagination.pages);
        }
      } catch (err) {
        setError("Failed to load archived ads.");
        if (!isLoadMore) setAds(null);
      } finally {
        setIsLoading(false);
      }
    },
    [],
  );

  const handleLoadMore = useCallback(() => {
    if (hasNextPage && !isLoading && lastParamsRef.current) {
      executeSearch(lastParamsRef.current, true);
    }
  }, [hasNextPage, isLoading, executeSearch]);

  const remainingCount =
    totalCount !== null ? Math.max(0, totalCount - fetchedCount) : null;
  const hasSearched = lastParamsRef.current !== null;

  return (
    <div className="min-h-screen bg-gray-50 pb-16 dark:bg-gray-900">
      <TitleSection
        icon={Database}
        badgeText="Global Archive"
        image={Search}
        imageColor="text-blue-500"
        highlightedText="Ad Master"
        remainingTitle="Database"
        auroraColors={["#3b82f6", "#60a5fa", "#93c5fd", "#bfdbfe"]}
      />

      <SearchFilters
        isLoading={isLoading}
        filters={AD_ARCHIVE_FILTERS}
        onSearch={(p) => executeSearch(p, false)}
      />

      <div className="mx-auto w-full px-4 md:px-6">
        {!hasSearched ? (
          <div className="rounded-2xl border border-gray-200 bg-white py-24 text-center shadow-sm dark:border-gray-700 dark:bg-gray-800">
            <Database className="mx-auto mb-5 h-14 w-14 text-gray-300 dark:text-gray-600" />
            <h3 className="text-xl font-semibold text-gray-700 dark:text-gray-300">
              Ready to Search
            </h3>
            <p className="mx-auto mt-2 max-w-sm text-gray-500">
              Click "Search" to explore the global ad database.
            </p>
          </div>
        ) : (
          <SearchResults
            isLoading={isLoading}
            error={error}
            totalCount={totalCount}
            searchResults={ads}
            hasNextPage={hasNextPage}
            remainingCount={remainingCount}
            handleLoadMore={handleLoadMore}
          />
        )}
      </div>
      <ScrollButtons />
    </div>
  );
}
