// @/components/adLibrary/archive/AdArchive.tsx
"use client";

import { useCallback, useRef, useState } from "react";
import { fetchAdArchive, FetchAdsParams } from "@/actions/adController";
import { AD_ARCHIVE_FILTERS } from "@/configuration/globalFilters";
import { Database, Search } from "lucide-react";
import { toast } from "sonner";

import { AdData } from "@/types/ad";
import { ScrollButtons } from "@/components/adTool/sharedComponents/ScrollButtons";
import SearchFilters from "@/components/adTool/sharedComponents/SearchFilters";
import SearchResults from "@/components/adTool/sharedComponents/SearchResults";
import TitleSection from "@/components/adTool/sharedComponents/TitleSection";

export default function AdArchive() {
  const [ads, setAds] = useState<AdData[] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [totalCount, setTotalCount] = useState<number | null>(null);
  const [fetchedCount, setFetchedCount] = useState<number>(0);
  const [hasNextPage, setHasNextPage] = useState<boolean>(false);

  // Tracks the explicit parameters generated by the form submission
  const lastParamsRef = useRef<URLSearchParams | null>(null);
  const currentPageRef = useRef<number>(1);

  const executeSearch = useCallback(
    async (params: URLSearchParams, isLoadMore = false) => {
      setIsLoading(true);
      setError(null);
      lastParamsRef.current = params; // Save params for "Load More"

      try {
        const pageToFetch = isLoadMore ? currentPageRef.current + 1 : 1;

        const fetchParams: FetchAdsParams = {
          page: pageToFetch,
          limit: 20,
          search: params.get("search") || undefined,
          pageName: params.get("pageName") || undefined,
          domain: params.get("domain") || undefined,
          pageCategory: params.get("pageCategory") || undefined,
          countries: params.getAll("countries"),
          platforms: params.getAll("platforms"),
          displayFormats: params.getAll("displayFormats"),
          ctaTypes: params.getAll("ctaTypes"),
          minCollation: params.get("collationCountMin")
            ? Number(params.get("collationCountMin"))
            : undefined,
          maxCollation: params.get("collationCountMax")
            ? Number(params.get("collationCountMax"))
            : undefined,
          startDateMin: params.get("startDateMin") || undefined,
          startDateMax: params.get("startDateMax") || undefined,
        };

        const result = await fetchAdArchive(fetchParams);

        if (result.error) {
          toast.error(result.error);
          throw new Error(result.error);
        }

        if (result.ads && result.pagination) {
          const extractedAds = result.ads.map((ad) => ad.adData);

          if (isLoadMore) {
            setAds((prev) => [...(prev || []), ...extractedAds]);
            setFetchedCount((prev) => prev + extractedAds.length);
          } else {
            setAds(extractedAds);
            setTotalCount(result.pagination.total);
            setFetchedCount(extractedAds.length);
          }

          currentPageRef.current = result.pagination.current;
          setHasNextPage(result.pagination.current < result.pagination.pages);
        }
      } catch (err) {
        setError("Failed to load archived ads.");
        if (!isLoadMore) setAds(null);
      } finally {
        setIsLoading(false);
      }
    },
    [],
  );

  const handleLoadMore = useCallback(() => {
    if (hasNextPage && !isLoading && lastParamsRef.current) {
      executeSearch(lastParamsRef.current, true);
    }
  }, [hasNextPage, isLoading, executeSearch]);

  const remainingCount =
    totalCount !== null ? Math.max(0, totalCount - fetchedCount) : null;
  const hasSearched = lastParamsRef.current !== null;

  return (
    <div className="min-h-screen space-y-2 bg-gradient-to-b from-gray-50 to-gray-100 pb-16 dark:from-gray-900 dark:to-gray-800">
      <TitleSection
        icon={Database}
        badgeText="Global Archive"
        image={Search}
        imageColor="text-blue-500"
        highlightedText="Ad Master"
        remainingTitle="Database"
        auroraColors={["#3b82f6", "#60a5fa", "#93c5fd", "#bfdbfe"]}
      />

      <SearchFilters
        isLoading={isLoading}
        filters={AD_ARCHIVE_FILTERS}
        onSearch={(p) => executeSearch(p, false)}
      />

      <SearchResults
        isLoading={isLoading}
        error={error}
        totalCount={totalCount}
        searchResults={ads}
        hasNextPage={hasNextPage}
        remainingCount={remainingCount}
        handleLoadMore={handleLoadMore}
      />

      <ScrollButtons />
    </div>
  );
}
