// @/config/globalFilters.ts
import {
  AtSign,
  Ban,
  Briefcase,
  CalendarDays,
  CircleCheckBig,
  CircleDollarSign,
  CircleDot,
  CircleSlash2,
  Dices,
  Facebook,
  FileText,
  Globe,
  Hash,
  Home,
  ImageIcon,
  Images,
  Instagram,
  KeyRound,
  Languages,
  Laugh,
  LayoutGrid,
  LayoutTemplate,
  MapPin,
  MegaphoneIcon,
  MessageCircleMore,
  MonitorSmartphone,
  MousePointerClick,
  Search,
  Tags,
  UserRound,
  Video,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type FilterType =
  | "text"
  | "checkbox"
  | "radio"
  | "date"
  | "date-range"
  | "number-range";

export interface FilterOption {
  value: string;
  label: string;
  icon?: string | LucideIcon;
}

export interface GlobalFilterConfig {
  id: string; // The URL parameter key
  label: string;
  type: FilterType;
  icon?: LucideIcon;
  placeholder?: string;
  options?: FilterOption[];
  searchable?: boolean;
}

// --- SHARED OPTIONS ---
export const countryOptions: FilterOption[] = [
  //{ value: "ALL", label: "All Countries", icon: "/flags/un.svg" },
  { value: "BR", label: "Brazil", icon: "/flags/br.svg" },
  { value: "IN", label: "India", icon: "/flags/in.svg" },
  { value: "GB", label: "United Kingdom", icon: "/flags/gb.svg" },
  { value: "US", label: "United States", icon: "/flags/us.svg" },
  { value: "CA", label: "Canada", icon: "/flags/ca.svg" },
  { value: "AR", label: "Argentina", icon: "/flags/ar.svg" },
  { value: "AU", label: "Australia", icon: "/flags/au.svg" },
  { value: "AT", label: "Austria", icon: "/flags/at.svg" },
  { value: "BE", label: "Belgium", icon: "/flags/be.svg" },
  { value: "CL", label: "Chile", icon: "/flags/cl.svg" },
  { value: "CN", label: "China", icon: "/flags/cn.svg" },
  { value: "CO", label: "Colombia", icon: "/flags/co.svg" },
  { value: "HR", label: "Croatia", icon: "/flags/hr.svg" },
  { value: "DK", label: "Denmark", icon: "/flags/dk.svg" },
  { value: "DO", label: "Dominican Republic", icon: "/flags/do.svg" },
  { value: "EG", label: "Egypt", icon: "/flags/eg.svg" },
  { value: "FI", label: "Finland", icon: "/flags/fi.svg" },
  { value: "FR", label: "France", icon: "/flags/fr.svg" },
  { value: "DE", label: "Germany", icon: "/flags/de.svg" },
  { value: "GR", label: "Greece", icon: "/flags/gr.svg" },
  { value: "HK", label: "Hong Kong", icon: "/flags/hk.svg" },
  { value: "ID", label: "Indonesia", icon: "/flags/id.svg" },
  { value: "IE", label: "Ireland", icon: "/flags/ie.svg" },
  {
    value: "IL",
    label: "Israel (Occupied Palestine)",
    icon: "/flags/ps.svg", //there is no israel X_X , it's an Occupied Palestinian Territory by a group of WAR Criminals  "/flags/il.svg"
  },
  { value: "IT", label: "Italy", icon: "/flags/it.svg" },
  { value: "JP", label: "Japan", icon: "/flags/jp.svg" },
  { value: "JO", label: "Jordan", icon: "/flags/jo.svg" },
  { value: "KW", label: "Kuwait", icon: "/flags/kw.svg" },
  { value: "LB", label: "Lebanon", icon: "/flags/lb.svg" },
  { value: "MY", label: "Malaysia", icon: "/flags/my.svg" },
  { value: "MX", label: "Mexico", icon: "/flags/mx.svg" },
  { value: "NL", label: "Netherlands", icon: "/flags/nl.svg" },
  { value: "NZ", label: "New Zealand", icon: "/flags/nz.svg" },
  { value: "NG", label: "Nigeria", icon: "/flags/ng.svg" },
  { value: "NO", label: "Norway", icon: "/flags/no.svg" },
  { value: "PK", label: "Pakistan", icon: "/flags/pk.svg" },
  { value: "PA", label: "Panama", icon: "/flags/pa.svg" },
  { value: "PE", label: "Peru", icon: "/flags/pe.svg" },
  { value: "PH", label: "Philippines", icon: "/flags/ph.svg" },
  { value: "PL", label: "Poland", icon: "/flags/pl.svg" },
  { value: "RU", label: "Russia", icon: "/flags/ru.svg" },
  { value: "SA", label: "Saudi Arabia", icon: "/flags/sa.svg" },
  { value: "RS", label: "Serbia", icon: "/flags/rs.svg" },
  { value: "SG", label: "Singapore", icon: "/flags/sg.svg" },
  { value: "ZA", label: "South Africa", icon: "/flags/za.svg" },
  { value: "KR", label: "South Korea", icon: "/flags/kr.svg" },
  { value: "ES", label: "Spain", icon: "/flags/es.svg" },
  { value: "SE", label: "Sweden", icon: "/flags/se.svg" },
  { value: "CH", label: "Switzerland", icon: "/flags/ch.svg" },
  { value: "TW", label: "Taiwan", icon: "/flags/tw.svg" },
  { value: "TH", label: "Thailand", icon: "/flags/th.svg" },
  { value: "TR", label: "Turkey", icon: "/flags/tr.svg" },
  { value: "AE", label: "United Arab Emirates", icon: "/flags/ae.svg" },
  { value: "VE", label: "Venezuela", icon: "/flags/ve.svg" },
  { value: "PT", label: "Portugal", icon: "/flags/pt.svg" },
  { value: "LU", label: "Luxembourg", icon: "/flags/lu.svg" },
  { value: "BG", label: "Bulgaria", icon: "/flags/bg.svg" },
  { value: "CZ", label: "Czech Republic", icon: "/flags/cz.svg" },
  { value: "SI", label: "Slovenia", icon: "/flags/si.svg" },
  { value: "IS", label: "Iceland", icon: "/flags/is.svg" },
  { value: "SK", label: "Slovakia", icon: "/flags/sk.svg" },
  { value: "LT", label: "Lithuania", icon: "/flags/lt.svg" },
  { value: "TT", label: "Trinidad and Tobago", icon: "/flags/tt.svg" },
  { value: "BD", label: "Bangladesh", icon: "/flags/bd.svg" },
  { value: "LK", label: "Sri Lanka", icon: "/flags/lk.svg" },
  { value: "KE", label: "Kenya", icon: "/flags/ke.svg" },
  { value: "HU", label: "Hungary", icon: "/flags/hu.svg" },
  { value: "MA", label: "Morocco", icon: "/flags/ma.svg" },
  { value: "CY", label: "Cyprus", icon: "/flags/cy.svg" },
  { value: "JM", label: "Jamaica", icon: "/flags/jm.svg" },
  { value: "EC", label: "Ecuador", icon: "/flags/ec.svg" },
  { value: "RO", label: "Romania", icon: "/flags/ro.svg" },
  { value: "BO", label: "Bolivia", icon: "/flags/bo.svg" },
  { value: "GT", label: "Guatemala", icon: "/flags/gt.svg" },
  { value: "CR", label: "Costa Rica", icon: "/flags/cr.svg" },
  { value: "QA", label: "Qatar", icon: "/flags/qa.svg" },
  { value: "SV", label: "El Salvador", icon: "/flags/sv.svg" },
  { value: "HN", label: "Honduras", icon: "/flags/hn.svg" },
  { value: "NI", label: "Nicaragua", icon: "/flags/ni.svg" },
  { value: "PY", label: "Paraguay", icon: "/flags/py.svg" },
  { value: "UY", label: "Uruguay", icon: "/flags/uy.svg" },
  { value: "PR", label: "Puerto Rico", icon: "/flags/pr.svg" },
  { value: "BA", label: "Bosnia and Herzegovina", icon: "/flags/ba.svg" },
  { value: "PS", label: "Palestine", icon: "/flags/ps.svg" },
  { value: "TN", label: "Tunisia", icon: "/flags/tn.svg" },
  { value: "BH", label: "Bahrain", icon: "/flags/bh.svg" },
  { value: "VN", label: "Vietnam", icon: "/flags/vn.svg" },
  { value: "GH", label: "Ghana", icon: "/flags/gh.svg" },
  { value: "MU", label: "Mauritius", icon: "/flags/mu.svg" },
  { value: "UA", label: "Ukraine", icon: "/flags/ua.svg" },
  { value: "MT", label: "Malta", icon: "/flags/mt.svg" },
  { value: "BS", label: "Bahamas", icon: "/flags/bs.svg" },
  { value: "MV", label: "Maldives", icon: "/flags/mv.svg" },
  { value: "OM", label: "Oman", icon: "/flags/om.svg" },
  { value: "MK", label: "North Macedonia", icon: "/flags/mk.svg" },
  { value: "LV", label: "Latvia", icon: "/flags/lv.svg" },
  { value: "EE", label: "Estonia", icon: "/flags/ee.svg" },
  { value: "IQ", label: "Iraq", icon: "/flags/iq.svg" },
  { value: "DZ", label: "Algeria", icon: "/flags/dz.svg" },
  { value: "AL", label: "Albania", icon: "/flags/al.svg" },
  { value: "NP", label: "Nepal", icon: "/flags/np.svg" },
  { value: "MO", label: "Macau", icon: "/flags/mo.svg" },
  { value: "ME", label: "Montenegro", icon: "/flags/me.svg" },
  { value: "SN", label: "Senegal", icon: "/flags/sn.svg" },
  { value: "GE", label: "Georgia", icon: "/flags/ge.svg" },
  { value: "BN", label: "Brunei", icon: "/flags/bn.svg" },
  { value: "UG", label: "Uganda", icon: "/flags/ug.svg" },
  { value: "GP", label: "Guadeloupe", icon: "/flags/gp.svg" },
  { value: "BB", label: "Barbados", icon: "/flags/bb.svg" },
  { value: "AZ", label: "Azerbaijan", icon: "/flags/az.svg" },
  { value: "TZ", label: "Tanzania", icon: "/flags/tz.svg" },
  { value: "LY", label: "Libya", icon: "/flags/ly.svg" },
  { value: "MQ", label: "Martinique", icon: "/flags/mq.svg" },
  { value: "CM", label: "Cameroon", icon: "/flags/cm.svg" },
  { value: "BW", label: "Botswana", icon: "/flags/bw.svg" },
  { value: "ET", label: "Ethiopia", icon: "/flags/et.svg" },
  { value: "KZ", label: "Kazakhstan", icon: "/flags/kz.svg" },
  { value: "NA", label: "Namibia", icon: "/flags/na.svg" },
  { value: "MG", label: "Madagascar", icon: "/flags/mg.svg" },
  { value: "NC", label: "New Caledonia", icon: "/flags/nc.svg" },
  { value: "MD", label: "Moldova", icon: "/flags/md.svg" },
  { value: "FJ", label: "Fiji", icon: "/flags/fj.svg" },
  { value: "BY", label: "Belarus", icon: "/flags/by.svg" },
  { value: "JE", label: "Jersey", icon: "/flags/je.svg" },
  { value: "GU", label: "Guam", icon: "/flags/gu.svg" },
  { value: "YE", label: "Yemen", icon: "/flags/ye.svg" },
  { value: "ZM", label: "Zambia", icon: "/flags/zm.svg" },
  { value: "IM", label: "Isle of Man", icon: "/flags/im.svg" },
  { value: "HT", label: "Haiti", icon: "/flags/ht.svg" },
  { value: "KH", label: "Cambodia", icon: "/flags/kh.svg" },
  { value: "AW", label: "Aruba", icon: "/flags/aw.svg" },
  { value: "PF", label: "French Polynesia", icon: "/flags/pf.svg" },
  { value: "AF", label: "Afghanistan", icon: "/flags/af.svg" },
  { value: "BM", label: "Bermuda", icon: "/flags/bm.svg" },
  { value: "GY", label: "Guyana", icon: "/flags/gy.svg" },
  { value: "AM", label: "Armenia", icon: "/flags/am.svg" },
  { value: "MW", label: "Malawi", icon: "/flags/mw.svg" },
  { value: "AG", label: "Antigua and Barbuda", icon: "/flags/ag.svg" },
  { value: "RW", label: "Rwanda", icon: "/flags/rw.svg" },
  { value: "GG", label: "Guernsey", icon: "/flags/gg.svg" },
  { value: "GM", label: "Gambia", icon: "/flags/gm.svg" },
  { value: "FO", label: "Faroe Islands", icon: "/flags/fo.svg" },
  { value: "LC", label: "Saint Lucia", icon: "/flags/lc.svg" },
  { value: "KY", label: "Cayman Islands", icon: "/flags/ky.svg" },
  { value: "BJ", label: "Benin", icon: "/flags/bj.svg" },
  { value: "AD", label: "Andorra", icon: "/flags/ad.svg" },
  { value: "GD", label: "Grenada", icon: "/flags/gd.svg" },
  { value: "VI", label: "U.S. Virgin Islands", icon: "/flags/vi.svg" },
  { value: "BZ", label: "Belize", icon: "/flags/bz.svg" },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    icon: "/flags/vc.svg",
  },
  { value: "MN", label: "Mongolia", icon: "/flags/mn.svg" },
  { value: "MZ", label: "Mozambique", icon: "/flags/mz.svg" },
  { value: "ML", label: "Mali", icon: "/flags/ml.svg" },
  { value: "AO", label: "Angola", icon: "/flags/ao.svg" },
  { value: "GF", label: "French Guiana", icon: "/flags/gf.svg" },
  { value: "UZ", label: "Uzbekistan", icon: "/flags/uz.svg" },
  { value: "DJ", label: "Djibouti", icon: "/flags/dj.svg" },
  { value: "BF", label: "Burkina Faso", icon: "/flags/bf.svg" },
  { value: "MC", label: "Monaco", icon: "/flags/mc.svg" },
  { value: "TG", label: "Togo", icon: "/flags/tg.svg" },
  { value: "GL", label: "Greenland", icon: "/flags/gl.svg" },
  { value: "GA", label: "Gabon", icon: "/flags/ga.svg" },
  { value: "GI", label: "Gibraltar", icon: "/flags/gi.svg" },
  {
    value: "CD",
    label: "Democratic Republic of the Congo",
    icon: "/flags/cd.svg",
  },
  { value: "KG", label: "Kyrgyzstan", icon: "/flags/kg.svg" },
  { value: "PG", label: "Papua New Guinea", icon: "/flags/pg.svg" },
  { value: "BT", label: "Bhutan", icon: "/flags/bt.svg" },
  { value: "KN", label: "Saint Kitts and Nevis", icon: "/flags/kn.svg" },
  { value: "SZ", label: "Eswatini", icon: "/flags/sz.svg" },
  { value: "LS", label: "Lesotho", icon: "/flags/ls.svg" },
  { value: "LA", label: "Laos", icon: "/flags/la.svg" },
  { value: "LI", label: "Liechtenstein", icon: "/flags/li.svg" },
  { value: "MP", label: "Northern Mariana Islands", icon: "/flags/mp.svg" },
  { value: "SR", label: "Suriname", icon: "/flags/sr.svg" },
  { value: "SC", label: "Seychelles", icon: "/flags/sc.svg" },
  { value: "VG", label: "British Virgin Islands", icon: "/flags/vg.svg" },
  { value: "TC", label: "Turks and Caicos Islands", icon: "/flags/tc.svg" },
  { value: "DM", label: "Dominica", icon: "/flags/dm.svg" },
  { value: "MR", label: "Mauritania", icon: "/flags/mr.svg" },
  { value: "AX", label: "Åland Islands", icon: "/flags/ax.svg" },
  { value: "SM", label: "San Marino", icon: "/flags/sm.svg" },
  { value: "SL", label: "Sierra Leone", icon: "/flags/sl.svg" },
  { value: "NE", label: "Niger", icon: "/flags/ne.svg" },
  { value: "CG", label: "Republic of the Congo", icon: "/flags/cg.svg" },
  { value: "AI", label: "Anguilla", icon: "/flags/ai.svg" },
  { value: "YT", label: "Mayotte", icon: "/flags/yt.svg" },
  { value: "CV", label: "Cape Verde", icon: "/flags/cv.svg" },
  { value: "GN", label: "Guinea", icon: "/flags/gn.svg" },
  { value: "TM", label: "Turkmenistan", icon: "/flags/tm.svg" },
  { value: "BI", label: "Burundi", icon: "/flags/bi.svg" },
  { value: "TJ", label: "Tajikistan", icon: "/flags/tj.svg" },
  { value: "VU", label: "Vanuatu", icon: "/flags/vu.svg" },
  { value: "SB", label: "Solomon Islands", icon: "/flags/sb.svg" },
  { value: "ER", label: "Eritrea", icon: "/flags/er.svg" },
  { value: "WS", label: "Samoa", icon: "/flags/ws.svg" },
  { value: "AS", label: "American Samoa", icon: "/flags/as.svg" },
  { value: "FK", label: "Falkland Islands", icon: "/flags/fk.svg" },
  { value: "GQ", label: "Equatorial Guinea", icon: "/flags/gq.svg" },
  { value: "TO", label: "Tonga", icon: "/flags/to.svg" },
  { value: "KM", label: "Comoros", icon: "/flags/km.svg" },
  { value: "PW", label: "Palau", icon: "/flags/pw.svg" },
  { value: "FM", label: "Micronesia", icon: "/flags/fm.svg" },
  { value: "CF", label: "Central African Republic", icon: "/flags/cf.svg" },
  { value: "SO", label: "Somalia", icon: "/flags/so.svg" },
  { value: "MH", label: "Marshall Islands", icon: "/flags/mh.svg" },
  { value: "VA", label: "Vatican City", icon: "/flags/va.svg" },
  { value: "TD", label: "Chad", icon: "/flags/td.svg" },
  { value: "KI", label: "Kiribati", icon: "/flags/ki.svg" },
  { value: "ST", label: "São Tomé and Príncipe", icon: "/flags/st.svg" },
  { value: "TV", label: "Tuvalu", icon: "/flags/tv.svg" },
  { value: "NR", label: "Nauru", icon: "/flags/nr.svg" },
  { value: "RE", label: "Réunion", icon: "/flags/re.svg" },
  { value: "LR", label: "Liberia", icon: "/flags/lr.svg" },
  { value: "ZW", label: "Zimbabwe", icon: "/flags/zw.svg" },
  { value: "CI", label: "Ivory Coast", icon: "/flags/ci.svg" },
  { value: "MM", label: "Myanmar", icon: "/flags/mm.svg" },
  { value: "AN", label: "Netherlands Antilles", icon: "/flags/an.svg" },
  { value: "AQ", label: "Antarctica", icon: "/flags/aq.svg" },
  { value: "BQ", label: "Caribbean Netherlands", icon: "/flags/bq.svg" },
  { value: "BV", label: "Bouvet Island", icon: "/flags/bv.svg" },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    icon: "/flags/io.svg",
  },
  { value: "CX", label: "Christmas Island", icon: "/flags/cx.svg" },
  { value: "CC", label: "Cocos (Keeling) Islands", icon: "/flags/cc.svg" },
  { value: "CK", label: "Cook Islands", icon: "/flags/ck.svg" },
  { value: "CW", label: "Curaçao", icon: "/flags/cw.svg" },
  { value: "TF", label: "French Southern Territories", icon: "/flags/tf.svg" },
  { value: "GW", label: "Guinea-Bissau", icon: "/flags/gw.svg" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
    icon: "/flags/hm.svg",
  },
  { value: "XK", label: "Kosovo", icon: "/flags/xk.svg" },
  { value: "MS", label: "Montserrat", icon: "/flags/ms.svg" },
  { value: "NU", label: "Niue", icon: "/flags/nu.svg" },
  { value: "NF", label: "Norfolk Island", icon: "/flags/nf.svg" },
  { value: "PN", label: "Pitcairn Islands", icon: "/flags/pn.svg" },
  { value: "BL", label: "Saint Barthélemy", icon: "/flags/bl.svg" },
  {
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    icon: "/flags/sh-hl.svg",
  },
  { value: "MF", label: "Saint Martin", icon: "/flags/mf.svg" },
  { value: "PM", label: "Saint Pierre and Miquelon", icon: "/flags/pm.svg" },
  { value: "SX", label: "Sint Maarten", icon: "/flags/sx.svg" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    icon: "/flags/gs.svg",
  },
  { value: "SS", label: "South Sudan", icon: "/flags/ss.svg" },
  { value: "SJ", label: "Svalbard and Jan Mayen", icon: "/flags/sj.svg" },
  { value: "TL", label: "East Timor", icon: "/flags/tl.svg" },
  { value: "TK", label: "Tokelau", icon: "/flags/tk.svg" },
  {
    value: "UM",
    label: "United States Minor Outlying Islands",
    icon: "/flags/us.svg",
  },
  { value: "WF", label: "Wallis and Futuna", icon: "/flags/wf.svg" },
  { value: "EH", label: "Western Sahara", icon: "/flags/eh.svg" },
  // Add remaining countries here...
];

const languageOptions: FilterOption[] = [
  { value: "aa", label: "Afar", icon: "Afar" },
  { value: "ab", label: "Abkhazian", icon: "Аҧсуа" },
  { value: "af", label: "Afrikaans", icon: "Afrikaans" },
  {
    value: "ak",
    label: "Akan",
    icon: "Akana",
  },
  {
    value: "am",
    label: "Amharic",
    icon: "አማርኛ",
  },
  {
    value: "an",
    label: "Aragonese",
    icon: "Aragonés",
  },
  {
    value: "ar",
    label: "Arabic",
    icon: "العربية",
  },
  {
    value: "as",
    label: "Assamese",
    icon: "অসমীয়া",
  },
  {
    value: "av",
    label: "Avar",
    icon: "Авар",
  },
  {
    value: "ay",
    label: "Aymara",
    icon: "Aymar",
  },
  {
    value: "az",
    label: "Azerbaijani",
    icon: "Azərbaycanca",
  },
  {
    value: "ba",
    label: "Bashkir",
    icon: "Башҡорт",
  },
  {
    value: "be",
    label: "Belarusian",
    icon: "Беларуская",
  },
  {
    value: "bg",
    label: "Bulgarian",
    icon: "Български",
  },
  {
    value: "bh",
    label: "Bihari",
    icon: "भोजपुरी",
  },
  {
    value: "bi",
    label: "Bislama",
    icon: "Bislama",
  },
  {
    value: "bm",
    label: "Bambara",
    icon: "Bamanankan",
  },
  {
    value: "bn",
    label: "Bengali",
    icon: "বাংলা",
  },
  {
    value: "bo",
    label: "Tibetan",
    icon: "བོད་ཡིག / Bod skad",
  },
  {
    value: "br",
    label: "Breton",
    icon: "Brezhoneg",
  },
  {
    value: "bs",
    label: "Bosnian",
    icon: "Bosanski",
  },
  {
    value: "ca",
    label: "Catalan",
    icon: "Català",
  },
  {
    value: "ce",
    label: "Chechen",
    icon: "Нохчийн",
  },
  {
    value: "ch",
    label: "Chamorro",
    icon: "Chamoru",
  },
  {
    value: "co",
    label: "Corsican",
    icon: "Corsu",
  },
  {
    value: "cr",
    label: "Cree",
    icon: "Nehiyaw",
  },
  {
    value: "cs",
    label: "Czech",
    icon: "Česky",
  },
  {
    value: "cu",
    label: "Old Church Slavonic / Old Bulgarian",
    icon: "словѣньскъ / slověnĭskŭ",
  },
  {
    value: "cv",
    label: "Chuvash",
    icon: "Чăваш",
  },
  {
    value: "cy",
    label: "Welsh",
    icon: "Cymraeg",
  },
  {
    value: "da",
    label: "Danish",
    icon: "Dansk",
  },
  {
    value: "de",
    label: "German",
    icon: "Deutsch",
  },
  {
    value: "dv",
    label: "Divehi",
    icon: "ދިވެހިބަސް",
  },
  {
    value: "dz",
    label: "Dzongkha",
    icon: "ཇོང་ཁ",
  },
  {
    value: "ee",
    label: "Ewe",
    icon: "Ɛʋɛ",
  },
  {
    value: "el",
    label: "Greek",
    icon: "Ελληνικά",
  },
  {
    value: "en",
    label: "English",
    icon: "English",
  },
  {
    value: "eo",
    label: "Esperanto",
    icon: "Esperanto",
  },
  {
    value: "es",
    label: "Spanish",
    icon: "Español",
  },
  {
    value: "et",
    label: "Estonian",
    icon: "Eesti",
  },
  {
    value: "eu",
    label: "Basque",
    icon: "Euskara",
  },
  {
    value: "fa",
    label: "Persian",
    icon: "فارسی",
  },
  {
    value: "ff",
    label: "Peul",
    icon: "Fulfulde",
  },
  {
    value: "fi",
    label: "Finnish",
    icon: "Suomi",
  },
  {
    value: "fj",
    label: "Fijian",
    icon: "Na Vosa Vakaviti",
  },
  {
    value: "fo",
    label: "Faroese",
    icon: "Føroyskt",
  },
  {
    value: "fr",
    label: "French",
    icon: "Français",
  },
  {
    value: "fy",
    label: "West Frisian",
    icon: "Frysk",
  },
  {
    value: "ga",
    label: "Irish",
    icon: "Gaeilge",
  },
  {
    value: "gd",
    label: "Scottish Gaelic",
    icon: "Gàidhlig",
  },
  {
    value: "gl",
    label: "Galician",
    icon: "Galego",
  },
  {
    value: "gn",
    label: "Guarani",
    icon: "Avañe'ẽ",
  },
  {
    value: "gu",
    label: "Gujarati",
    icon: "ગુજરાતી",
  },
  {
    value: "gv",
    label: "Manx",
    icon: "Gaelg",
  },
  {
    value: "ha",
    label: "Hausa",
    icon: "هَوُسَ",
  },
  {
    value: "he",
    label: "Hebrew",
    icon: "עברית",
  },
  {
    value: "hi",
    label: "Hindi",
    icon: "हिन्दी",
  },
  {
    value: "ho",
    label: "Hiri Motu",
    icon: "Hiri Motu",
  },
  {
    value: "hr",
    label: "Croatian",
    icon: "Hrvatski",
  },
  {
    value: "ht",
    label: "Haitian",
    icon: "Krèyol ayisyen",
  },
  {
    value: "hu",
    label: "Hungarian",
    icon: "Magyar",
  },
  {
    value: "hy",
    label: "Armenian",
    icon: "Հայերեն",
  },
  {
    value: "hz",
    label: "Herero",
    icon: "Otsiherero",
  },
  {
    value: "ia",
    label: "Interlingua",
    icon: "Interlingua",
  },
  {
    value: "id",
    label: "Indonesian",
    icon: "Bahasa Indonesia",
  },
  {
    value: "ie",
    label: "Interlingue",
    icon: "Interlingue",
  },
  {
    value: "ig",
    label: "Igbo",
    icon: "Igbo",
  },
  {
    value: "ii",
    label: "Sichuan Yi",
    icon: "ꆇꉙ / 四川彝语",
  },
  {
    value: "ik",
    label: "Inupiak",
    icon: "Iñupiak",
  },
  {
    value: "io",
    label: "Ido",
    icon: "Ido",
  },
  {
    value: "is",
    label: "Icelandic",
    icon: "Íslenska",
  },
  {
    value: "it",
    label: "Italian",
    icon: "Italiano",
  },
  {
    value: "iu",
    label: "Inuktitut",
    icon: "ᐃᓄᒃᑎᑐᑦ",
  },
  {
    value: "ja",
    label: "Japanese",
    icon: "日本語",
  },
  {
    value: "jv",
    label: "Javanese",
    icon: "Basa Jawa",
  },
  {
    value: "ka",
    label: "Georgian",
    icon: "ქართული",
  },
  {
    value: "kg",
    label: "Kongo",
    icon: "KiKongo",
  },
  {
    value: "ki",
    label: "Kikuyu",
    icon: "Gĩkũyũ",
  },
  {
    value: "kj",
    label: "Kuanyama",
    icon: "Kuanyama",
  },
  {
    value: "kk",
    label: "Kazakh",
    icon: "Қазақша",
  },
  {
    value: "kl",
    label: "Greenlandic",
    icon: "Kalaallisut",
  },
  {
    value: "km",
    label: "Cambodian",
    icon: "ភាសាខ្មែរ",
  },
  {
    value: "kn",
    label: "Kannada",
    icon: "ಕನ್ನಡ",
  },
  {
    value: "ko",
    label: "Korean",
    icon: "한국어",
  },
  {
    value: "kr",
    label: "Kanuri",
    icon: "Kanuri",
  },
  {
    value: "ks",
    label: "Kashmiri",
    icon: "कश्मीरी / كشميري",
  },
  {
    value: "ku",
    label: "Kurdish",
    icon: "Kurdî / كوردی",
  },
  {
    value: "kv",
    label: "Komi",
    icon: "Коми",
  },
  {
    value: "kw",
    label: "Cornish",
    icon: "Kernewek",
  },
  {
    value: "ky",
    label: "Kirghiz",
    icon: "Kırgızca / Кыргызча",
  },
  {
    value: "la",
    label: "Latin",
    icon: "Latina",
  },
  {
    value: "lb",
    label: "Luxembourgish",
    icon: "Lëtzebuergesch",
  },
  {
    value: "lg",
    label: "Ganda",
    icon: "Luganda",
  },
  {
    value: "li",
    label: "Limburgian",
    icon: "Limburgs",
  },
  {
    value: "ln",
    label: "Lingala",
    icon: "Lingála",
  },
  {
    value: "lo",
    label: "Laotian",
    icon: "ລາວ / Pha xa lao",
  },
  {
    value: "lt",
    label: "Lithuanian",
    icon: "Lietuvių",
  },
  {
    value: "lu",
    label: "Luba-Katanga",
    icon: "Tshiluba",
  },
  {
    value: "lv",
    label: "Latvian",
    icon: "Latviešu",
  },
  {
    value: "mg",
    label: "Malagasy",
    icon: "Malagasy",
  },
  {
    value: "mh",
    label: "Marshallese",
    icon: "Kajin Majel / Ebon",
  },
  {
    value: "mi",
    label: "Maori",
    icon: "Māori",
  },
  {
    value: "mk",
    label: "Macedonian",
    icon: "Македонски",
  },
  {
    value: "ml",
    label: "Malayalam",
    icon: "മലയാളം",
  },
  {
    value: "mn",
    label: "Mongolian",
    icon: "Монгол",
  },
  {
    value: "mo",
    label: "Moldovan",
    icon: "Moldovenească",
  },
  {
    value: "mr",
    label: "Marathi",
    icon: "मराठी",
  },
  {
    value: "ms",
    label: "Malay",
    icon: "Bahasa Melayu",
  },
  {
    value: "mt",
    label: "Maltese",
    icon: "bil-Malti",
  },
  {
    value: "my",
    label: "Burmese",
    icon: "မြန်မာစာ",
  },
  {
    value: "na",
    label: "Nauruan",
    icon: "Dorerin Naoero",
  },
  {
    value: "nb",
    label: "Norwegian Bokmål",
    icon: "Norsk bokmål",
  },
  {
    value: "nd",
    label: "North Ndebele",
    icon: "Sindebele",
  },
  {
    value: "ne",
    label: "Nepali",
    icon: "नेपाली",
  },
  {
    value: "ng",
    label: "Ndonga",
    icon: "Oshiwambo",
  },
  {
    value: "nl",
    label: "Dutch",
    icon: "Nederlands",
  },
  {
    value: "nn",
    label: "Norwegian Nynorsk",
    icon: "Norsk nynorsk",
  },
  {
    value: "no",
    label: "Norwegian",
    icon: "Norsk",
  },
  {
    value: "nr",
    label: "South Ndebele",
    icon: "isiNdebele",
  },
  {
    value: "nv",
    label: "Navajo",
    icon: "Diné bizaad",
  },
  {
    value: "ny",
    label: "Chichewa",
    icon: "Chi-Chewa",
  },
  {
    value: "oc",
    label: "Occitan",
    icon: "Occitan",
  },
  {
    value: "oj",
    label: "Ojibwa",
    icon: "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin",
  },
  {
    value: "om",
    label: "Oromo",
    icon: "Oromoo",
  },
  {
    value: "or",
    label: "Oriya",
    icon: "ଓଡ଼ିଆ",
  },
  {
    value: "os",
    label: "Ossetian / Ossetic",
    icon: "Иронау",
  },
  {
    value: "pa",
    label: "Panjabi / Punjabi",
    icon: "ਪੰਜਾਬੀ / पंजाबी / پنجابي",
  },
  {
    value: "pi",
    label: "Pali",
    icon: "Pāli / पाऴि",
  },
  {
    value: "pl",
    label: "Polish",
    icon: "Polski",
  },
  {
    value: "ps",
    label: "Pashto",
    icon: "پښتو",
  },
  {
    value: "pt",
    label: "Portuguese",
    icon: "Português",
  },
  {
    value: "qu",
    label: "Quechua",
    icon: "Runa Simi",
  },
  {
    value: "rm",
    label: "Raeto Romance",
    icon: "Rumantsch",
  },
  {
    value: "rn",
    label: "Kirundi",
    icon: "Kirundi",
  },
  {
    value: "ro",
    label: "Romanian",
    icon: "Română",
  },
  {
    value: "ru",
    label: "Russian",
    icon: "Русский",
  },
  {
    value: "rw",
    label: "Rwandi",
    icon: "Kinyarwandi",
  },
  {
    value: "sa",
    label: "Sanskrit",
    icon: "संस्कृतम्",
  },
  {
    value: "sc",
    label: "Sardinian",
    icon: "Sardu",
  },
  {
    value: "sd",
    label: "Sindhi",
    icon: "सिनधि",
  },
  {
    value: "se",
    label: "Northern Sami",
    icon: "Sámegiella",
  },
  {
    value: "sg",
    label: "Sango",
    icon: "Sängö",
  },
  {
    value: "sh",
    label: "Serbo-Croatian",
    icon: "Srpskohrvatski / Српскохрватски",
  },
  {
    value: "si",
    label: "Sinhalese",
    icon: "සිංහල",
  },
  {
    value: "sk",
    label: "Slovak",
    icon: "Slovenčina",
  },
  {
    value: "sl",
    label: "Slovenian",
    icon: "Slovenščina",
  },
  {
    value: "sm",
    label: "Samoan",
    icon: "Gagana Samoa",
  },
  {
    value: "sn",
    label: "Shona",
    icon: "chiShona",
  },
  {
    value: "so",
    label: "Somalia",
    icon: "Soomaaliga",
  },
  {
    value: "sq",
    label: "Albanian",
    icon: "Shqip",
  },
  {
    value: "sr",
    label: "Serbian",
    icon: "Српски",
  },
  {
    value: "ss",
    label: "Swati",
    icon: "SiSwati",
  },
  {
    value: "st",
    label: "Southern Sotho",
    icon: "Sesotho",
  },
  {
    value: "su",
    label: "Sundanese",
    icon: "Basa Sunda",
  },
  {
    value: "sv",
    label: "Swedish",
    icon: "Svenska",
  },
  {
    value: "sw",
    label: "Swahili",
    icon: "Kiswahili",
  },
  {
    value: "ta",
    label: "Tamil",
    icon: "தமிழ்",
  },
  {
    value: "te",
    label: "Telugu",
    icon: "తెలుగు",
  },
  {
    value: "tg",
    label: "Tajik",
    icon: "Тоҷикӣ",
  },
  {
    value: "th",
    label: "Thai",
    icon: "ไทย / Phasa Thai",
  },
  {
    value: "ti",
    label: "Tigrinya",
    icon: "ትግርኛ",
  },
  {
    value: "tk",
    label: "Turkmen",
    icon: "Туркмен / تركمن",
  },
  {
    value: "tl",
    label: "Tagalog / Filipino",
    icon: "Tagalog",
  },
  {
    value: "tn",
    label: "Tswana",
    icon: "Setswana",
  },
  {
    value: "to",
    label: "Tonga",
    icon: "Lea Faka-Tonga",
  },
  {
    value: "tr",
    label: "Turkish",
    icon: "Türkçe",
  },
  {
    value: "ts",
    label: "Tsonga",
    icon: "Xitsonga",
  },
  {
    value: "tt",
    label: "Tatar",
    icon: "Tatarça",
  },
  {
    value: "tw",
    label: "Twi",
    icon: "Twi",
  },
  {
    value: "ty",
    label: "Tahitian",
    icon: "Reo Mā`ohi",
  },
  {
    value: "ug",
    label: "Uyghur",
    icon: "Uyƣurqə / ئۇيغۇرچە",
  },
  {
    value: "uk",
    label: "Ukrainian",
    icon: "Українська",
  },
  {
    value: "ur",
    label: "Urdu",
    icon: "اردو",
  },
  {
    value: "uz",
    label: "Uzbek",
    icon: "Ўзбек",
  },
  {
    value: "ve",
    label: "Venda",
    icon: "Tshivenḓa",
  },
  {
    value: "vi",
    label: "Vietnamese",
    icon: "Tiếng Việt",
  },
  {
    value: "vo",
    label: "Volapük",
    icon: "Volapük",
  },
  {
    value: "wa",
    label: "Walloon",
    icon: "Walon",
  },
  {
    value: "wo",
    label: "Wolof",
    icon: "Wollof",
  },
  {
    value: "xh",
    label: "Xhosa",
    icon: "isiXhosa",
  },
  {
    value: "yi",
    label: "Yiddish",
    icon: "ייִדיש",
  },
  {
    value: "yo",
    label: "Yoruba",
    icon: "Yorùbá",
  },
  {
    value: "za",
    label: "Zhuang",
    icon: "Cuengh / Tôô / 壮语",
  },
  {
    value: "zh",
    label: "Chinese",
    icon: "中文",
  },
  {
    value: "zu",
    label: "Zulu",
    icon: "isiZulu",
  },
];

const platformOptions: FilterOption[] = [
  { value: "FACEBOOK", label: "Facebook", icon: Facebook },
  { value: "INSTAGRAM", label: "Instagram", icon: Instagram },
  { value: "AUDIENCE_NETWORK", label: "Audience Network", icon: UserRound },
  { value: "MESSENGER", label: "Messenger", icon: Zap },
  { value: "WHATSAPP", label: "WhatsApp", icon: MessageCircleMore },
  { value: "THREADS", label: "Threads", icon: AtSign },
];

const categoryKeywords: FilterOption[] = [
  // Home & Living
  { label: "Home & Decor", value: "decor" },
  { label: "Garden & Plants", value: "garden" },
  { label: "Furniture", value: "furniture" },
  { label: "Kitchen & Dining", value: "kitchen" },
  { label: "Bathroom", value: "bathroom" },
  { label: "Lighting", value: "lighting" },
  { label: "Storage & Organization", value: "storage" },
  { label: "Bedding", value: "bedding" },
  { label: "Appliances", value: "appliances" },
  { label: "Rugs & Flooring", value: "flooring" },

  // Fashion & Accessories
  { label: "Women's Fashion", value: "women" },
  { label: "Men's Fashion", value: "men" },
  { label: "Fashion Accessories", value: "accessories" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Shoes & Footwear", value: "shoes" },
  { label: "Bags & Purses", value: "bags" },
  { label: "Watches", value: "watches" },
  { label: "Hats", value: "hats" },
  { label: "Scarves", value: "scarves" },

  // Beauty & Health
  { label: "Beauty", value: "beauty" },
  { label: "Skincare", value: "skincare" },
  { label: "Health & Wellness", value: "health" },
  { label: "Personal Care", value: "personal" },
  { label: "Cosmetics", value: "makeup" },
  { label: "Hair Care", value: "hair" },
  { label: "Fragrances", value: "fragrance" },
  { label: "Bath & Body", value: "bath" },
  { label: "Supplements", value: "supplements" },

  // Electronics & Tech
  { label: "Electronics", value: "electronics" },
  { label: "Phones & Tablets", value: "mobile" },
  { label: "Computers & Laptops", value: "computer" },
  { label: "Gaming", value: "gaming" },
  { label: "Tech Accessories", value: "gadgets" },
  { label: "Smart Home", value: "smart" },
  { label: "Audio Equipment", value: "audio" },
  { label: "Cameras", value: "camera" },
  { label: "Wearable Tech", value: "wearables" },

  // Kids & Baby
  { label: "Baby Products", value: "baby" },
  { label: "Kids Fashion", value: "kids" },
  { label: "Toys & Games", value: "toys" },
  { label: "School Supplies", value: "school" },
  { label: "Nursery", value: "nursery" },
  { label: "Children's Books", value: "childrens" },
  { label: "Maternity", value: "maternity" },

  // Food & Beverages
  { label: "Food", value: "food" },
  { label: "Beverages", value: "beverages" },
  { label: "Snacks", value: "snacks" },
  { label: "Groceries", value: "grocery" },
  { label: "Baking", value: "baking" },
  { label: "Coffee & Tea", value: "coffee" },
  { label: "Specialty Foods", value: "gourmet" },
  { label: "Organic", value: "organic" },

  // Sports & Outdoors
  { label: "Sports Equipment", value: "sports" },
  { label: "Outdoor Gear", value: "outdoor" },
  { label: "Fitness", value: "fitness" },
  { label: "Camping", value: "camping" },
  { label: "Hiking", value: "hiking" },
  { label: "Water Sports", value: "watersports" },
  { label: "Cycling", value: "cycling" },
  { label: "Winter Sports", value: "winter" },

  // Pets
  { label: "Pet Supplies", value: "petcare" },
  { label: "Dog Products", value: "dog" },
  { label: "Cat Products", value: "cat" },
  { label: "Pet Food", value: "petfood" },
  { label: "Fish & Aquarium", value: "aquarium" },
  { label: "Small Pets", value: "smallpets" },
  { label: "Bird Supplies", value: "birds" },

  // Entertainment
  { label: "Books", value: "books" },
  { label: "Movies & TV", value: "movies" },
  { label: "Music", value: "instruments" },
  { label: "Digital Content", value: "digital" },
  { label: "Board Games", value: "boardgames" },
  { label: "Streaming", value: "streaming" },
  { label: "Vinyl Records", value: "vinyl" },

  // Automotive
  { label: "Car Accessories", value: "car" },
  { label: "Auto Parts", value: "autoparts" },
  { label: "Tools & Equipment", value: "tools" },
  { label: "Motorcycle", value: "motorcycle" },
  { label: "Vehicle Care", value: "vehiclecare" },
  { label: "Tires & Wheels", value: "tires" },
  { label: "Electric Vehicles", value: "ev" },

  // Art & Hobbies
  { label: "Art Supplies", value: "art" },
  { label: "Crafting", value: "craft" },
  { label: "Musical Instruments", value: "musical" },
  { label: "Collectibles", value: "collectibles" },
  { label: "Photography", value: "photo" },
  { label: "Model Building", value: "models" },
  { label: "Sewing & Fabric", value: "sewing" },
  { label: "Gardening", value: "gardening" },

  // Office & Professional
  { label: "Office Supplies", value: "office" },
  { label: "Stationery", value: "stationery" },
  { label: "Printers & Ink", value: "printers" },
  { label: "Business Equipment", value: "business" },
  { label: "Professional Services", value: "services" },
  { label: "Education", value: "education" },

  // Special Categories
  { label: "Gifts & Occasions", value: "gifts" },
  { label: "Holiday & Seasonal", value: "holiday" },
  { label: "Travel & Luggage", value: "travel" },
  { label: "Vintage & Antiques", value: "vintage" },
  { label: "Handmade", value: "handmade" },
  { label: "Sustainability", value: "eco" },
  { label: "Local Products", value: "local" },
  { label: "Limited Edition", value: "limited" },
  { label: "Luxury", value: "luxury" },
];

// ==========================================
// 🔵 META AD BROWSER FILTERS
// ==========================================
export const META_FILTERS: GlobalFilterConfig[] = [
  {
    id: "q",
    label: "Search Query",
    type: "text",
    icon: Search,
    placeholder: "Search ads, brands, keywords...",
  },
  {
    id: "search_type",
    label: "Keyword Match",
    type: "radio",
    icon: KeyRound,
    options: [
      { value: "KEYWORD_UNORDERED", label: "Keyword Unordered", icon: Dices },
      {
        value: "KEYWORD_EXACT_PHRASE",
        label: "Keyword Exact Phrase",
        icon: KeyRound,
      },
    ],
  },
  {
    id: "active_status",
    label: "Status",
    type: "radio",
    icon: CircleDot,
    options: [
      { value: "ALL", label: "Active & Inactive", icon: CircleDot },
      { value: "ACTIVE", label: "Active", icon: CircleCheckBig },
      { value: "INACTIVE", label: "Inactive", icon: CircleSlash2 },
    ],
  },
  {
    id: "ad_type",
    label: "Category",
    type: "radio",
    icon: LayoutGrid,
    options: [
      { value: "ALL", label: "All Ads", icon: LayoutGrid },
      {
        value: "CREDIT_ADS",
        label: "Financial & Credit",
        icon: CircleDollarSign,
      },
      { value: "EMPLOYMENT_ADS", label: "Jobs & Employment", icon: Briefcase },
      { value: "HOUSING_ADS", label: "Real Estate", icon: Home },
      {
        value: "POLITICAL_AND_ISSUE_ADS",
        label: "Politics & Issues",
        icon: MegaphoneIcon,
      },
    ],
  },
  {
    id: "countries",
    label: "Countries",
    type: "checkbox",
    icon: MapPin,
    searchable: true,
    options: countryOptions,
  },
  {
    id: "media_type",
    label: "Media",
    type: "radio",
    icon: Images,
    options: [
      { value: "ALL", label: "All Media", icon: Images },
      { value: "IMAGE", label: "Images", icon: ImageIcon },
      { value: "MEME", label: "Memes", icon: Laugh },
      { value: "IMAGE_AND_MEME", label: "Images & Memes", icon: Images },
      { value: "VIDEO", label: "Videos", icon: Video },
      { value: "NONE", label: "No Image/Video", icon: Ban },
    ],
  },
  {
    id: "publisher_platforms",
    label: "Platforms",
    type: "checkbox",
    icon: MonitorSmartphone,
    options: platformOptions,
  },
  {
    id: "content_languages",
    label: "Language",
    type: "checkbox",
    icon: Languages,
    searchable: true,
    options: languageOptions,
  },
  { id: "start_date", label: "Start Date", type: "date", icon: CalendarDays },
  { id: "end_date", label: "End Date", type: "date", icon: CalendarDays },
];

// ==========================================
// 🟠 AD ARCHIVE (DATABASE) FILTERS
// ==========================================
export const AD_ARCHIVE_FILTERS: GlobalFilterConfig[] = [
  {
    id: "search",
    label: "Global Search",
    type: "text",
    icon: Search,
    placeholder: "Search keywords or phrases...",
  },
  {
    id: "pageName",
    label: "Page Name",
    type: "text",
    icon: FileText,
    placeholder: "Page Name (e.g., Dine New Zealand)",
  },
  {
    id: "domain",
    label: "Domain",
    type: "text",
    icon: Globe,
    placeholder: "Domain (e.g., myshop)",
  },
  {
    id: "pageCategory",
    label: "Page Category",
    type: "text",
    icon: Tags,
    placeholder: "Page Category (e.g., Pet Supplies)",
  },

  {
    id: "countries",
    label: "Countries",
    type: "checkbox",
    icon: MapPin,
    searchable: true,
    options: countryOptions,
  },
  {
    id: "startDate",
    label: "Date Started",
    type: "date-range",
    icon: CalendarDays,
  },
  {
    id: "collationCount",
    label: "Duplicate Count",
    type: "number-range",
    icon: Hash,
  },

  {
    id: "platforms",
    label: "Platforms",
    type: "checkbox",
    icon: MonitorSmartphone,
    options: platformOptions,
  },
  {
    id: "displayFormats",
    label: "Format",
    type: "checkbox",
    icon: LayoutTemplate,
    options: [
      { label: "Image", value: "IMAGE" },
      { label: "Video", value: "VIDEO" },
      { label: "DCO (Dynamic)", value: "DCO" },
      { label: "Carousel", value: "CAROUSEL" },
    ],
  },
  {
    id: "ctaTypes",
    label: "CTA Button",
    type: "checkbox",
    icon: MousePointerClick,
    options: [
      { label: "Apply Now", value: "APPLY_NOW" },
      { label: "Contact Us", value: "CONTACT_US" },
      { label: "Download", value: "DOWNLOAD" },
      { label: "Learn More", value: "LEARN_MORE" },
      { label: "Get Quote", value: "GET_QUOTE" },
      { label: "Send Message", value: "SEND_MESSAGE" },
      { label: "Shop Now", value: "SHOP_NOW" },
      { label: "Sign Up", value: "SIGN_UP" },
      { label: "Watch More", value: "WATCH_MORE" },
      { label: "Send WhatsApp Message", value: "SEND_WHATSAPP_MESSAGE" },
      { label: "Find Your Groups", value: "FIND_YOUR_GROUPS" },
      { label: "Try in Camera", value: "TRY_IN_CAMERA" },
      { label: "Get Directions", value: "GET_DIRECTIONS" },
      { label: "Book Now", value: "BOOK_NOW" },
      { label: "Subscribe", value: "SUBSCRIBE" },
      { label: "Order Now", value: "ORDER_NOW" },
      { label: "Listen Now", value: "LISTEN_NOW" },
      { label: "Request Time", value: "REQUEST_TIME" },
      { label: "Dial Code", value: "DIAL_CODE" },
      { label: "Get Showtimes", value: "GET_SHOWTIMES" },
      { label: "See Menu", value: "SEE_MENU" },
      { label: "Call Now", value: "CALL_NOW" },
    ],
  },
];
