// @filter-config.ts
import {
  AlignEndVertical,
  Ban,
  Briefcase,
  CircleCheck,
  CircleCheckBig,
  CircleDollarSign,
  CircleDot,
  CircleSlash2,
  CircleX,
  Dices,
  Facebook,
  Home,
  ImageIcon,
  Images,
  Instagram,
  KeyRound,
  Laugh,
  LayoutGrid,
  MegaphoneIcon,
  MessageCircle,
  SmileIcon,
  Users,
  Video,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// 📝 Type definitions for filter options
export interface FilterOption {
  value: string;
  label: string;
  icon?: string | LucideIcon;
  native?: string;
}

export interface FilterConfig {
  key: string;
  paramKey: string;
  label: string;
  icon: string;
  multiSelect?: boolean;
  options?: FilterOption[];
}

// 🔍 Search types
const searchTypes: FilterOption[] = [
  { value: "KEYWORD_UNORDERED", label: "Keyword Unordered", icon: Dices },
  {
    value: "KEYWORD_EXACT_PHRASE",
    label: "Keyword Exact Phrase",
    icon: KeyRound,
  },
];

// 📋 Categories
const categories: FilterOption[] = [
  { value: "ALL", label: "All Ads", icon: LayoutGrid },
  {
    value: "CREDIT_ADS",
    label: "Financial, Credit & Services ",
    icon: CircleDollarSign,
  },
  {
    value: "EMPLOYMENT_ADS",
    label: "Jobs, Career & Employment",
    icon: Briefcase,
  },
  {
    value: "HOUSING_ADS",
    label: "Properties & Real Estate",
    icon: Home,
  },
  {
    value: "POLITICAL_AND_ISSUE_ADS",
    label: "Politics, Elections & Issues",
    icon: MegaphoneIcon,
  },
];

// 🌎 Countries
export const countryCodesAlpha2Flag: FilterOption[] = [
  //{ value: "ALL", label: "All Countries", icon: "/flags/un.svg" },
  { value: "BR", label: "Brazil", icon: "/flags/br.svg" },
  { value: "IN", label: "India", icon: "/flags/in.svg" },
  { value: "GB", label: "United Kingdom", icon: "/flags/gb.svg" },
  { value: "US", label: "United States", icon: "/flags/us.svg" },
  { value: "CA", label: "Canada", icon: "/flags/ca.svg" },
  { value: "AR", label: "Argentina", icon: "/flags/ar.svg" },
  { value: "AU", label: "Australia", icon: "/flags/au.svg" },
  { value: "AT", label: "Austria", icon: "/flags/at.svg" },
  { value: "BE", label: "Belgium", icon: "/flags/be.svg" },
  { value: "CL", label: "Chile", icon: "/flags/cl.svg" },
  { value: "CN", label: "China", icon: "/flags/cn.svg" },
  { value: "CO", label: "Colombia", icon: "/flags/co.svg" },
  { value: "HR", label: "Croatia", icon: "/flags/hr.svg" },
  { value: "DK", label: "Denmark", icon: "/flags/dk.svg" },
  { value: "DO", label: "Dominican Republic", icon: "/flags/do.svg" },
  { value: "EG", label: "Egypt", icon: "/flags/eg.svg" },
  { value: "FI", label: "Finland", icon: "/flags/fi.svg" },
  { value: "FR", label: "France", icon: "/flags/fr.svg" },
  { value: "DE", label: "Germany", icon: "/flags/de.svg" },
  { value: "GR", label: "Greece", icon: "/flags/gr.svg" },
  { value: "HK", label: "Hong Kong", icon: "/flags/hk.svg" },
  { value: "ID", label: "Indonesia", icon: "/flags/id.svg" },
  { value: "IE", label: "Ireland", icon: "/flags/ie.svg" },
  {
    value: "IL",
    label: "Israel (Occupied Palestine)",
    icon: "/flags/ps.svg", //there is no israel X_X , it's an Occupied Palestinian Territory by a group of WAR Criminals  "/flags/il.svg"
  },
  { value: "IT", label: "Italy", icon: "/flags/it.svg" },
  { value: "JP", label: "Japan", icon: "/flags/jp.svg" },
  { value: "JO", label: "Jordan", icon: "/flags/jo.svg" },
  { value: "KW", label: "Kuwait", icon: "/flags/kw.svg" },
  { value: "LB", label: "Lebanon", icon: "/flags/lb.svg" },
  { value: "MY", label: "Malaysia", icon: "/flags/my.svg" },
  { value: "MX", label: "Mexico", icon: "/flags/mx.svg" },
  { value: "NL", label: "Netherlands", icon: "/flags/nl.svg" },
  { value: "NZ", label: "New Zealand", icon: "/flags/nz.svg" },
  { value: "NG", label: "Nigeria", icon: "/flags/ng.svg" },
  { value: "NO", label: "Norway", icon: "/flags/no.svg" },
  { value: "PK", label: "Pakistan", icon: "/flags/pk.svg" },
  { value: "PA", label: "Panama", icon: "/flags/pa.svg" },
  { value: "PE", label: "Peru", icon: "/flags/pe.svg" },
  { value: "PH", label: "Philippines", icon: "/flags/ph.svg" },
  { value: "PL", label: "Poland", icon: "/flags/pl.svg" },
  { value: "RU", label: "Russia", icon: "/flags/ru.svg" },
  { value: "SA", label: "Saudi Arabia", icon: "/flags/sa.svg" },
  { value: "RS", label: "Serbia", icon: "/flags/rs.svg" },
  { value: "SG", label: "Singapore", icon: "/flags/sg.svg" },
  { value: "ZA", label: "South Africa", icon: "/flags/za.svg" },
  { value: "KR", label: "South Korea", icon: "/flags/kr.svg" },
  { value: "ES", label: "Spain", icon: "/flags/es.svg" },
  { value: "SE", label: "Sweden", icon: "/flags/se.svg" },
  { value: "CH", label: "Switzerland", icon: "/flags/ch.svg" },
  { value: "TW", label: "Taiwan", icon: "/flags/tw.svg" },
  { value: "TH", label: "Thailand", icon: "/flags/th.svg" },
  { value: "TR", label: "Turkey", icon: "/flags/tr.svg" },
  { value: "AE", label: "United Arab Emirates", icon: "/flags/ae.svg" },
  { value: "VE", label: "Venezuela", icon: "/flags/ve.svg" },
  { value: "PT", label: "Portugal", icon: "/flags/pt.svg" },
  { value: "LU", label: "Luxembourg", icon: "/flags/lu.svg" },
  { value: "BG", label: "Bulgaria", icon: "/flags/bg.svg" },
  { value: "CZ", label: "Czech Republic", icon: "/flags/cz.svg" },
  { value: "SI", label: "Slovenia", icon: "/flags/si.svg" },
  { value: "IS", label: "Iceland", icon: "/flags/is.svg" },
  { value: "SK", label: "Slovakia", icon: "/flags/sk.svg" },
  { value: "LT", label: "Lithuania", icon: "/flags/lt.svg" },
  { value: "TT", label: "Trinidad and Tobago", icon: "/flags/tt.svg" },
  { value: "BD", label: "Bangladesh", icon: "/flags/bd.svg" },
  { value: "LK", label: "Sri Lanka", icon: "/flags/lk.svg" },
  { value: "KE", label: "Kenya", icon: "/flags/ke.svg" },
  { value: "HU", label: "Hungary", icon: "/flags/hu.svg" },
  { value: "MA", label: "Morocco", icon: "/flags/ma.svg" },
  { value: "CY", label: "Cyprus", icon: "/flags/cy.svg" },
  { value: "JM", label: "Jamaica", icon: "/flags/jm.svg" },
  { value: "EC", label: "Ecuador", icon: "/flags/ec.svg" },
  { value: "RO", label: "Romania", icon: "/flags/ro.svg" },
  { value: "BO", label: "Bolivia", icon: "/flags/bo.svg" },
  { value: "GT", label: "Guatemala", icon: "/flags/gt.svg" },
  { value: "CR", label: "Costa Rica", icon: "/flags/cr.svg" },
  { value: "QA", label: "Qatar", icon: "/flags/qa.svg" },
  { value: "SV", label: "El Salvador", icon: "/flags/sv.svg" },
  { value: "HN", label: "Honduras", icon: "/flags/hn.svg" },
  { value: "NI", label: "Nicaragua", icon: "/flags/ni.svg" },
  { value: "PY", label: "Paraguay", icon: "/flags/py.svg" },
  { value: "UY", label: "Uruguay", icon: "/flags/uy.svg" },
  { value: "PR", label: "Puerto Rico", icon: "/flags/pr.svg" },
  { value: "BA", label: "Bosnia and Herzegovina", icon: "/flags/ba.svg" },
  { value: "PS", label: "Palestine", icon: "/flags/ps.svg" },
  { value: "TN", label: "Tunisia", icon: "/flags/tn.svg" },
  { value: "BH", label: "Bahrain", icon: "/flags/bh.svg" },
  { value: "VN", label: "Vietnam", icon: "/flags/vn.svg" },
  { value: "GH", label: "Ghana", icon: "/flags/gh.svg" },
  { value: "MU", label: "Mauritius", icon: "/flags/mu.svg" },
  { value: "UA", label: "Ukraine", icon: "/flags/ua.svg" },
  { value: "MT", label: "Malta", icon: "/flags/mt.svg" },
  { value: "BS", label: "Bahamas", icon: "/flags/bs.svg" },
  { value: "MV", label: "Maldives", icon: "/flags/mv.svg" },
  { value: "OM", label: "Oman", icon: "/flags/om.svg" },
  { value: "MK", label: "North Macedonia", icon: "/flags/mk.svg" },
  { value: "LV", label: "Latvia", icon: "/flags/lv.svg" },
  { value: "EE", label: "Estonia", icon: "/flags/ee.svg" },
  { value: "IQ", label: "Iraq", icon: "/flags/iq.svg" },
  { value: "DZ", label: "Algeria", icon: "/flags/dz.svg" },
  { value: "AL", label: "Albania", icon: "/flags/al.svg" },
  { value: "NP", label: "Nepal", icon: "/flags/np.svg" },
  { value: "MO", label: "Macau", icon: "/flags/mo.svg" },
  { value: "ME", label: "Montenegro", icon: "/flags/me.svg" },
  { value: "SN", label: "Senegal", icon: "/flags/sn.svg" },
  { value: "GE", label: "Georgia", icon: "/flags/ge.svg" },
  { value: "BN", label: "Brunei", icon: "/flags/bn.svg" },
  { value: "UG", label: "Uganda", icon: "/flags/ug.svg" },
  { value: "GP", label: "Guadeloupe", icon: "/flags/gp.svg" },
  { value: "BB", label: "Barbados", icon: "/flags/bb.svg" },
  { value: "AZ", label: "Azerbaijan", icon: "/flags/az.svg" },
  { value: "TZ", label: "Tanzania", icon: "/flags/tz.svg" },
  { value: "LY", label: "Libya", icon: "/flags/ly.svg" },
  { value: "MQ", label: "Martinique", icon: "/flags/mq.svg" },
  { value: "CM", label: "Cameroon", icon: "/flags/cm.svg" },
  { value: "BW", label: "Botswana", icon: "/flags/bw.svg" },
  { value: "ET", label: "Ethiopia", icon: "/flags/et.svg" },
  { value: "KZ", label: "Kazakhstan", icon: "/flags/kz.svg" },
  { value: "NA", label: "Namibia", icon: "/flags/na.svg" },
  { value: "MG", label: "Madagascar", icon: "/flags/mg.svg" },
  { value: "NC", label: "New Caledonia", icon: "/flags/nc.svg" },
  { value: "MD", label: "Moldova", icon: "/flags/md.svg" },
  { value: "FJ", label: "Fiji", icon: "/flags/fj.svg" },
  { value: "BY", label: "Belarus", icon: "/flags/by.svg" },
  { value: "JE", label: "Jersey", icon: "/flags/je.svg" },
  { value: "GU", label: "Guam", icon: "/flags/gu.svg" },
  { value: "YE", label: "Yemen", icon: "/flags/ye.svg" },
  { value: "ZM", label: "Zambia", icon: "/flags/zm.svg" },
  { value: "IM", label: "Isle of Man", icon: "/flags/im.svg" },
  { value: "HT", label: "Haiti", icon: "/flags/ht.svg" },
  { value: "KH", label: "Cambodia", icon: "/flags/kh.svg" },
  { value: "AW", label: "Aruba", icon: "/flags/aw.svg" },
  { value: "PF", label: "French Polynesia", icon: "/flags/pf.svg" },
  { value: "AF", label: "Afghanistan", icon: "/flags/af.svg" },
  { value: "BM", label: "Bermuda", icon: "/flags/bm.svg" },
  { value: "GY", label: "Guyana", icon: "/flags/gy.svg" },
  { value: "AM", label: "Armenia", icon: "/flags/am.svg" },
  { value: "MW", label: "Malawi", icon: "/flags/mw.svg" },
  { value: "AG", label: "Antigua and Barbuda", icon: "/flags/ag.svg" },
  { value: "RW", label: "Rwanda", icon: "/flags/rw.svg" },
  { value: "GG", label: "Guernsey", icon: "/flags/gg.svg" },
  { value: "GM", label: "Gambia", icon: "/flags/gm.svg" },
  { value: "FO", label: "Faroe Islands", icon: "/flags/fo.svg" },
  { value: "LC", label: "Saint Lucia", icon: "/flags/lc.svg" },
  { value: "KY", label: "Cayman Islands", icon: "/flags/ky.svg" },
  { value: "BJ", label: "Benin", icon: "/flags/bj.svg" },
  { value: "AD", label: "Andorra", icon: "/flags/ad.svg" },
  { value: "GD", label: "Grenada", icon: "/flags/gd.svg" },
  { value: "VI", label: "U.S. Virgin Islands", icon: "/flags/vi.svg" },
  { value: "BZ", label: "Belize", icon: "/flags/bz.svg" },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    icon: "/flags/vc.svg",
  },
  { value: "MN", label: "Mongolia", icon: "/flags/mn.svg" },
  { value: "MZ", label: "Mozambique", icon: "/flags/mz.svg" },
  { value: "ML", label: "Mali", icon: "/flags/ml.svg" },
  { value: "AO", label: "Angola", icon: "/flags/ao.svg" },
  { value: "GF", label: "French Guiana", icon: "/flags/gf.svg" },
  { value: "UZ", label: "Uzbekistan", icon: "/flags/uz.svg" },
  { value: "DJ", label: "Djibouti", icon: "/flags/dj.svg" },
  { value: "BF", label: "Burkina Faso", icon: "/flags/bf.svg" },
  { value: "MC", label: "Monaco", icon: "/flags/mc.svg" },
  { value: "TG", label: "Togo", icon: "/flags/tg.svg" },
  { value: "GL", label: "Greenland", icon: "/flags/gl.svg" },
  { value: "GA", label: "Gabon", icon: "/flags/ga.svg" },
  { value: "GI", label: "Gibraltar", icon: "/flags/gi.svg" },
  {
    value: "CD",
    label: "Democratic Republic of the Congo",
    icon: "/flags/cd.svg",
  },
  { value: "KG", label: "Kyrgyzstan", icon: "/flags/kg.svg" },
  { value: "PG", label: "Papua New Guinea", icon: "/flags/pg.svg" },
  { value: "BT", label: "Bhutan", icon: "/flags/bt.svg" },
  { value: "KN", label: "Saint Kitts and Nevis", icon: "/flags/kn.svg" },
  { value: "SZ", label: "Eswatini", icon: "/flags/sz.svg" },
  { value: "LS", label: "Lesotho", icon: "/flags/ls.svg" },
  { value: "LA", label: "Laos", icon: "/flags/la.svg" },
  { value: "LI", label: "Liechtenstein", icon: "/flags/li.svg" },
  { value: "MP", label: "Northern Mariana Islands", icon: "/flags/mp.svg" },
  { value: "SR", label: "Suriname", icon: "/flags/sr.svg" },
  { value: "SC", label: "Seychelles", icon: "/flags/sc.svg" },
  { value: "VG", label: "British Virgin Islands", icon: "/flags/vg.svg" },
  { value: "TC", label: "Turks and Caicos Islands", icon: "/flags/tc.svg" },
  { value: "DM", label: "Dominica", icon: "/flags/dm.svg" },
  { value: "MR", label: "Mauritania", icon: "/flags/mr.svg" },
  { value: "AX", label: "Åland Islands", icon: "/flags/ax.svg" },
  { value: "SM", label: "San Marino", icon: "/flags/sm.svg" },
  { value: "SL", label: "Sierra Leone", icon: "/flags/sl.svg" },
  { value: "NE", label: "Niger", icon: "/flags/ne.svg" },
  { value: "CG", label: "Republic of the Congo", icon: "/flags/cg.svg" },
  { value: "AI", label: "Anguilla", icon: "/flags/ai.svg" },
  { value: "YT", label: "Mayotte", icon: "/flags/yt.svg" },
  { value: "CV", label: "Cape Verde", icon: "/flags/cv.svg" },
  { value: "GN", label: "Guinea", icon: "/flags/gn.svg" },
  { value: "TM", label: "Turkmenistan", icon: "/flags/tm.svg" },
  { value: "BI", label: "Burundi", icon: "/flags/bi.svg" },
  { value: "TJ", label: "Tajikistan", icon: "/flags/tj.svg" },
  { value: "VU", label: "Vanuatu", icon: "/flags/vu.svg" },
  { value: "SB", label: "Solomon Islands", icon: "/flags/sb.svg" },
  { value: "ER", label: "Eritrea", icon: "/flags/er.svg" },
  { value: "WS", label: "Samoa", icon: "/flags/ws.svg" },
  { value: "AS", label: "American Samoa", icon: "/flags/as.svg" },
  { value: "FK", label: "Falkland Islands", icon: "/flags/fk.svg" },
  { value: "GQ", label: "Equatorial Guinea", icon: "/flags/gq.svg" },
  { value: "TO", label: "Tonga", icon: "/flags/to.svg" },
  { value: "KM", label: "Comoros", icon: "/flags/km.svg" },
  { value: "PW", label: "Palau", icon: "/flags/pw.svg" },
  { value: "FM", label: "Micronesia", icon: "/flags/fm.svg" },
  { value: "CF", label: "Central African Republic", icon: "/flags/cf.svg" },
  { value: "SO", label: "Somalia", icon: "/flags/so.svg" },
  { value: "MH", label: "Marshall Islands", icon: "/flags/mh.svg" },
  { value: "VA", label: "Vatican City", icon: "/flags/va.svg" },
  { value: "TD", label: "Chad", icon: "/flags/td.svg" },
  { value: "KI", label: "Kiribati", icon: "/flags/ki.svg" },
  { value: "ST", label: "São Tomé and Príncipe", icon: "/flags/st.svg" },
  { value: "TV", label: "Tuvalu", icon: "/flags/tv.svg" },
  { value: "NR", label: "Nauru", icon: "/flags/nr.svg" },
  { value: "RE", label: "Réunion", icon: "/flags/re.svg" },
  { value: "LR", label: "Liberia", icon: "/flags/lr.svg" },
  { value: "ZW", label: "Zimbabwe", icon: "/flags/zw.svg" },
  { value: "CI", label: "Ivory Coast", icon: "/flags/ci.svg" },
  { value: "MM", label: "Myanmar", icon: "/flags/mm.svg" },
  { value: "AN", label: "Netherlands Antilles", icon: "/flags/an.svg" },
  { value: "AQ", label: "Antarctica", icon: "/flags/aq.svg" },
  { value: "BQ", label: "Caribbean Netherlands", icon: "/flags/bq.svg" },
  { value: "BV", label: "Bouvet Island", icon: "/flags/bv.svg" },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    icon: "/flags/io.svg",
  },
  { value: "CX", label: "Christmas Island", icon: "/flags/cx.svg" },
  { value: "CC", label: "Cocos (Keeling) Islands", icon: "/flags/cc.svg" },
  { value: "CK", label: "Cook Islands", icon: "/flags/ck.svg" },
  { value: "CW", label: "Curaçao", icon: "/flags/cw.svg" },
  { value: "TF", label: "French Southern Territories", icon: "/flags/tf.svg" },
  { value: "GW", label: "Guinea-Bissau", icon: "/flags/gw.svg" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
    icon: "/flags/hm.svg",
  },
  { value: "XK", label: "Kosovo", icon: "/flags/xk.svg" },
  { value: "MS", label: "Montserrat", icon: "/flags/ms.svg" },
  { value: "NU", label: "Niue", icon: "/flags/nu.svg" },
  { value: "NF", label: "Norfolk Island", icon: "/flags/nf.svg" },
  { value: "PN", label: "Pitcairn Islands", icon: "/flags/pn.svg" },
  { value: "BL", label: "Saint Barthélemy", icon: "/flags/bl.svg" },
  {
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    icon: "/flags/sh-hl.svg",
  },
  { value: "MF", label: "Saint Martin", icon: "/flags/mf.svg" },
  { value: "PM", label: "Saint Pierre and Miquelon", icon: "/flags/pm.svg" },
  { value: "SX", label: "Sint Maarten", icon: "/flags/sx.svg" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    icon: "/flags/gs.svg",
  },
  { value: "SS", label: "South Sudan", icon: "/flags/ss.svg" },
  { value: "SJ", label: "Svalbard and Jan Mayen", icon: "/flags/sj.svg" },
  { value: "TL", label: "East Timor", icon: "/flags/tl.svg" },
  { value: "TK", label: "Tokelau", icon: "/flags/tk.svg" },
  {
    value: "UM",
    label: "United States Minor Outlying Islands",
    icon: "/flags/us.svg",
  },
  { value: "WF", label: "Wallis and Futuna", icon: "/flags/wf.svg" },
  { value: "EH", label: "Western Sahara", icon: "/flags/eh.svg" },
];

// 🏷️ Category as keywords
const categoryKeywords: FilterOption[] = [
  // Home & Living
  { label: "Home & Decor", value: "decor" },
  { label: "Garden & Plants", value: "garden" },
  { label: "Furniture", value: "furniture" },
  { label: "Kitchen & Dining", value: "kitchen" },
  { label: "Bathroom", value: "bathroom" },
  { label: "Lighting", value: "lighting" },
  { label: "Storage & Organization", value: "storage" },
  { label: "Bedding", value: "bedding" },
  { label: "Appliances", value: "appliances" },
  { label: "Rugs & Flooring", value: "flooring" },

  // Fashion & Accessories
  { label: "Women's Fashion", value: "women" },
  { label: "Men's Fashion", value: "men" },
  { label: "Fashion Accessories", value: "accessories" },
  { label: "Jewelry", value: "jewelry" },
  { label: "Shoes & Footwear", value: "shoes" },
  { label: "Bags & Purses", value: "bags" },
  { label: "Watches", value: "watches" },
  { label: "Hats", value: "hats" },
  { label: "Scarves", value: "scarves" },

  // Beauty & Health
  { label: "Beauty", value: "beauty" },
  { label: "Skincare", value: "skincare" },
  { label: "Health & Wellness", value: "health" },
  { label: "Personal Care", value: "personal" },
  { label: "Cosmetics", value: "makeup" },
  { label: "Hair Care", value: "hair" },
  { label: "Fragrances", value: "fragrance" },
  { label: "Bath & Body", value: "bath" },
  { label: "Supplements", value: "supplements" },

  // Electronics & Tech
  { label: "Electronics", value: "electronics" },
  { label: "Phones & Tablets", value: "mobile" },
  { label: "Computers & Laptops", value: "computer" },
  { label: "Gaming", value: "gaming" },
  { label: "Tech Accessories", value: "gadgets" },
  { label: "Smart Home", value: "smart" },
  { label: "Audio Equipment", value: "audio" },
  { label: "Cameras", value: "camera" },
  { label: "Wearable Tech", value: "wearables" },

  // Kids & Baby
  { label: "Baby Products", value: "baby" },
  { label: "Kids Fashion", value: "kids" },
  { label: "Toys & Games", value: "toys" },
  { label: "School Supplies", value: "school" },
  { label: "Nursery", value: "nursery" },
  { label: "Children's Books", value: "childrens" },
  { label: "Maternity", value: "maternity" },

  // Food & Beverages
  { label: "Food", value: "food" },
  { label: "Beverages", value: "beverages" },
  { label: "Snacks", value: "snacks" },
  { label: "Groceries", value: "grocery" },
  { label: "Baking", value: "baking" },
  { label: "Coffee & Tea", value: "coffee" },
  { label: "Specialty Foods", value: "gourmet" },
  { label: "Organic", value: "organic" },

  // Sports & Outdoors
  { label: "Sports Equipment", value: "sports" },
  { label: "Outdoor Gear", value: "outdoor" },
  { label: "Fitness", value: "fitness" },
  { label: "Camping", value: "camping" },
  { label: "Hiking", value: "hiking" },
  { label: "Water Sports", value: "watersports" },
  { label: "Cycling", value: "cycling" },
  { label: "Winter Sports", value: "winter" },

  // Pets
  { label: "Pet Supplies", value: "petcare" },
  { label: "Dog Products", value: "dog" },
  { label: "Cat Products", value: "cat" },
  { label: "Pet Food", value: "petfood" },
  { label: "Fish & Aquarium", value: "aquarium" },
  { label: "Small Pets", value: "smallpets" },
  { label: "Bird Supplies", value: "birds" },

  // Entertainment
  { label: "Books", value: "books" },
  { label: "Movies & TV", value: "movies" },
  { label: "Music", value: "instruments" },
  { label: "Digital Content", value: "digital" },
  { label: "Board Games", value: "boardgames" },
  { label: "Streaming", value: "streaming" },
  { label: "Vinyl Records", value: "vinyl" },

  // Automotive
  { label: "Car Accessories", value: "car" },
  { label: "Auto Parts", value: "autoparts" },
  { label: "Tools & Equipment", value: "tools" },
  { label: "Motorcycle", value: "motorcycle" },
  { label: "Vehicle Care", value: "vehiclecare" },
  { label: "Tires & Wheels", value: "tires" },
  { label: "Electric Vehicles", value: "ev" },

  // Art & Hobbies
  { label: "Art Supplies", value: "art" },
  { label: "Crafting", value: "craft" },
  { label: "Musical Instruments", value: "musical" },
  { label: "Collectibles", value: "collectibles" },
  { label: "Photography", value: "photo" },
  { label: "Model Building", value: "models" },
  { label: "Sewing & Fabric", value: "sewing" },
  { label: "Gardening", value: "gardening" },

  // Office & Professional
  { label: "Office Supplies", value: "office" },
  { label: "Stationery", value: "stationery" },
  { label: "Printers & Ink", value: "printers" },
  { label: "Business Equipment", value: "business" },
  { label: "Professional Services", value: "services" },
  { label: "Education", value: "education" },

  // Special Categories
  { label: "Gifts & Occasions", value: "gifts" },
  { label: "Holiday & Seasonal", value: "holiday" },
  { label: "Travel & Luggage", value: "travel" },
  { label: "Vintage & Antiques", value: "vintage" },
  { label: "Handmade", value: "handmade" },
  { label: "Sustainability", value: "eco" },
  { label: "Local Products", value: "local" },
  { label: "Limited Edition", value: "limited" },
  { label: "Luxury", value: "luxury" },
];

// 🗣️ Languages
const languages: FilterOption[] = [
  { value: "aa", label: "Afar", native: "Afar" },
  { value: "ab", label: "Abkhazian", native: "Аҧсуа" },
  { value: "af", label: "Afrikaans", native: "Afrikaans" },
  {
    value: "ak",
    label: "Akan",
    native: "Akana",
  },
  {
    value: "am",
    label: "Amharic",
    native: "አማርኛ",
  },
  {
    value: "an",
    label: "Aragonese",
    native: "Aragonés",
  },
  {
    value: "ar",
    label: "Arabic",
    native: "العربية",
  },
  {
    value: "as",
    label: "Assamese",
    native: "অসমীয়া",
  },
  {
    value: "av",
    label: "Avar",
    native: "Авар",
  },
  {
    value: "ay",
    label: "Aymara",
    native: "Aymar",
  },
  {
    value: "az",
    label: "Azerbaijani",
    native: "Azərbaycanca",
  },
  {
    value: "ba",
    label: "Bashkir",
    native: "Башҡорт",
  },
  {
    value: "be",
    label: "Belarusian",
    native: "Беларуская",
  },
  {
    value: "bg",
    label: "Bulgarian",
    native: "Български",
  },
  {
    value: "bh",
    label: "Bihari",
    native: "भोजपुरी",
  },
  {
    value: "bi",
    label: "Bislama",
    native: "Bislama",
  },
  {
    value: "bm",
    label: "Bambara",
    native: "Bamanankan",
  },
  {
    value: "bn",
    label: "Bengali",
    native: "বাংলা",
  },
  {
    value: "bo",
    label: "Tibetan",
    native: "བོད་ཡིག / Bod skad",
  },
  {
    value: "br",
    label: "Breton",
    native: "Brezhoneg",
  },
  {
    value: "bs",
    label: "Bosnian",
    native: "Bosanski",
  },
  {
    value: "ca",
    label: "Catalan",
    native: "Català",
  },
  {
    value: "ce",
    label: "Chechen",
    native: "Нохчийн",
  },
  {
    value: "ch",
    label: "Chamorro",
    native: "Chamoru",
  },
  {
    value: "co",
    label: "Corsican",
    native: "Corsu",
  },
  {
    value: "cr",
    label: "Cree",
    native: "Nehiyaw",
  },
  {
    value: "cs",
    label: "Czech",
    native: "Česky",
  },
  {
    value: "cu",
    label: "Old Church Slavonic / Old Bulgarian",
    native: "словѣньскъ / slověnĭskŭ",
  },
  {
    value: "cv",
    label: "Chuvash",
    native: "Чăваш",
  },
  {
    value: "cy",
    label: "Welsh",
    native: "Cymraeg",
  },
  {
    value: "da",
    label: "Danish",
    native: "Dansk",
  },
  {
    value: "de",
    label: "German",
    native: "Deutsch",
  },
  {
    value: "dv",
    label: "Divehi",
    native: "ދިވެހިބަސް",
  },
  {
    value: "dz",
    label: "Dzongkha",
    native: "ཇོང་ཁ",
  },
  {
    value: "ee",
    label: "Ewe",
    native: "Ɛʋɛ",
  },
  {
    value: "el",
    label: "Greek",
    native: "Ελληνικά",
  },
  {
    value: "en",
    label: "English",
    native: "English",
  },
  {
    value: "eo",
    label: "Esperanto",
    native: "Esperanto",
  },
  {
    value: "es",
    label: "Spanish",
    native: "Español",
  },
  {
    value: "et",
    label: "Estonian",
    native: "Eesti",
  },
  {
    value: "eu",
    label: "Basque",
    native: "Euskara",
  },
  {
    value: "fa",
    label: "Persian",
    native: "فارسی",
  },
  {
    value: "ff",
    label: "Peul",
    native: "Fulfulde",
  },
  {
    value: "fi",
    label: "Finnish",
    native: "Suomi",
  },
  {
    value: "fj",
    label: "Fijian",
    native: "Na Vosa Vakaviti",
  },
  {
    value: "fo",
    label: "Faroese",
    native: "Føroyskt",
  },
  {
    value: "fr",
    label: "French",
    native: "Français",
  },
  {
    value: "fy",
    label: "West Frisian",
    native: "Frysk",
  },
  {
    value: "ga",
    label: "Irish",
    native: "Gaeilge",
  },
  {
    value: "gd",
    label: "Scottish Gaelic",
    native: "Gàidhlig",
  },
  {
    value: "gl",
    label: "Galician",
    native: "Galego",
  },
  {
    value: "gn",
    label: "Guarani",
    native: "Avañe'ẽ",
  },
  {
    value: "gu",
    label: "Gujarati",
    native: "ગુજરાતી",
  },
  {
    value: "gv",
    label: "Manx",
    native: "Gaelg",
  },
  {
    value: "ha",
    label: "Hausa",
    native: "هَوُسَ",
  },
  {
    value: "he",
    label: "Hebrew",
    native: "עברית",
  },
  {
    value: "hi",
    label: "Hindi",
    native: "हिन्दी",
  },
  {
    value: "ho",
    label: "Hiri Motu",
    native: "Hiri Motu",
  },
  {
    value: "hr",
    label: "Croatian",
    native: "Hrvatski",
  },
  {
    value: "ht",
    label: "Haitian",
    native: "Krèyol ayisyen",
  },
  {
    value: "hu",
    label: "Hungarian",
    native: "Magyar",
  },
  {
    value: "hy",
    label: "Armenian",
    native: "Հայերեն",
  },
  {
    value: "hz",
    label: "Herero",
    native: "Otsiherero",
  },
  {
    value: "ia",
    label: "Interlingua",
    native: "Interlingua",
  },
  {
    value: "id",
    label: "Indonesian",
    native: "Bahasa Indonesia",
  },
  {
    value: "ie",
    label: "Interlingue",
    native: "Interlingue",
  },
  {
    value: "ig",
    label: "Igbo",
    native: "Igbo",
  },
  {
    value: "ii",
    label: "Sichuan Yi",
    native: "ꆇꉙ / 四川彝语",
  },
  {
    value: "ik",
    label: "Inupiak",
    native: "Iñupiak",
  },
  {
    value: "io",
    label: "Ido",
    native: "Ido",
  },
  {
    value: "is",
    label: "Icelandic",
    native: "Íslenska",
  },
  {
    value: "it",
    label: "Italian",
    native: "Italiano",
  },
  {
    value: "iu",
    label: "Inuktitut",
    native: "ᐃᓄᒃᑎᑐᑦ",
  },
  {
    value: "ja",
    label: "Japanese",
    native: "日本語",
  },
  {
    value: "jv",
    label: "Javanese",
    native: "Basa Jawa",
  },
  {
    value: "ka",
    label: "Georgian",
    native: "ქართული",
  },
  {
    value: "kg",
    label: "Kongo",
    native: "KiKongo",
  },
  {
    value: "ki",
    label: "Kikuyu",
    native: "Gĩkũyũ",
  },
  {
    value: "kj",
    label: "Kuanyama",
    native: "Kuanyama",
  },
  {
    value: "kk",
    label: "Kazakh",
    native: "Қазақша",
  },
  {
    value: "kl",
    label: "Greenlandic",
    native: "Kalaallisut",
  },
  {
    value: "km",
    label: "Cambodian",
    native: "ភាសាខ្មែរ",
  },
  {
    value: "kn",
    label: "Kannada",
    native: "ಕನ್ನಡ",
  },
  {
    value: "ko",
    label: "Korean",
    native: "한국어",
  },
  {
    value: "kr",
    label: "Kanuri",
    native: "Kanuri",
  },
  {
    value: "ks",
    label: "Kashmiri",
    native: "कश्मीरी / كشميري",
  },
  {
    value: "ku",
    label: "Kurdish",
    native: "Kurdî / كوردی",
  },
  {
    value: "kv",
    label: "Komi",
    native: "Коми",
  },
  {
    value: "kw",
    label: "Cornish",
    native: "Kernewek",
  },
  {
    value: "ky",
    label: "Kirghiz",
    native: "Kırgızca / Кыргызча",
  },
  {
    value: "la",
    label: "Latin",
    native: "Latina",
  },
  {
    value: "lb",
    label: "Luxembourgish",
    native: "Lëtzebuergesch",
  },
  {
    value: "lg",
    label: "Ganda",
    native: "Luganda",
  },
  {
    value: "li",
    label: "Limburgian",
    native: "Limburgs",
  },
  {
    value: "ln",
    label: "Lingala",
    native: "Lingála",
  },
  {
    value: "lo",
    label: "Laotian",
    native: "ລາວ / Pha xa lao",
  },
  {
    value: "lt",
    label: "Lithuanian",
    native: "Lietuvių",
  },
  {
    value: "lu",
    label: "Luba-Katanga",
    native: "Tshiluba",
  },
  {
    value: "lv",
    label: "Latvian",
    native: "Latviešu",
  },
  {
    value: "mg",
    label: "Malagasy",
    native: "Malagasy",
  },
  {
    value: "mh",
    label: "Marshallese",
    native: "Kajin Majel / Ebon",
  },
  {
    value: "mi",
    label: "Maori",
    native: "Māori",
  },
  {
    value: "mk",
    label: "Macedonian",
    native: "Македонски",
  },
  {
    value: "ml",
    label: "Malayalam",
    native: "മലയാളം",
  },
  {
    value: "mn",
    label: "Mongolian",
    native: "Монгол",
  },
  {
    value: "mo",
    label: "Moldovan",
    native: "Moldovenească",
  },
  {
    value: "mr",
    label: "Marathi",
    native: "मराठी",
  },
  {
    value: "ms",
    label: "Malay",
    native: "Bahasa Melayu",
  },
  {
    value: "mt",
    label: "Maltese",
    native: "bil-Malti",
  },
  {
    value: "my",
    label: "Burmese",
    native: "မြန်မာစာ",
  },
  {
    value: "na",
    label: "Nauruan",
    native: "Dorerin Naoero",
  },
  {
    value: "nb",
    label: "Norwegian Bokmål",
    native: "Norsk bokmål",
  },
  {
    value: "nd",
    label: "North Ndebele",
    native: "Sindebele",
  },
  {
    value: "ne",
    label: "Nepali",
    native: "नेपाली",
  },
  {
    value: "ng",
    label: "Ndonga",
    native: "Oshiwambo",
  },
  {
    value: "nl",
    label: "Dutch",
    native: "Nederlands",
  },
  {
    value: "nn",
    label: "Norwegian Nynorsk",
    native: "Norsk nynorsk",
  },
  {
    value: "no",
    label: "Norwegian",
    native: "Norsk",
  },
  {
    value: "nr",
    label: "South Ndebele",
    native: "isiNdebele",
  },
  {
    value: "nv",
    label: "Navajo",
    native: "Diné bizaad",
  },
  {
    value: "ny",
    label: "Chichewa",
    native: "Chi-Chewa",
  },
  {
    value: "oc",
    label: "Occitan",
    native: "Occitan",
  },
  {
    value: "oj",
    label: "Ojibwa",
    native: "ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin",
  },
  {
    value: "om",
    label: "Oromo",
    native: "Oromoo",
  },
  {
    value: "or",
    label: "Oriya",
    native: "ଓଡ଼ିଆ",
  },
  {
    value: "os",
    label: "Ossetian / Ossetic",
    native: "Иронау",
  },
  {
    value: "pa",
    label: "Panjabi / Punjabi",
    native: "ਪੰਜਾਬੀ / पंजाबी / پنجابي",
  },
  {
    value: "pi",
    label: "Pali",
    native: "Pāli / पाऴि",
  },
  {
    value: "pl",
    label: "Polish",
    native: "Polski",
  },
  {
    value: "ps",
    label: "Pashto",
    native: "پښتو",
  },
  {
    value: "pt",
    label: "Portuguese",
    native: "Português",
  },
  {
    value: "qu",
    label: "Quechua",
    native: "Runa Simi",
  },
  {
    value: "rm",
    label: "Raeto Romance",
    native: "Rumantsch",
  },
  {
    value: "rn",
    label: "Kirundi",
    native: "Kirundi",
  },
  {
    value: "ro",
    label: "Romanian",
    native: "Română",
  },
  {
    value: "ru",
    label: "Russian",
    native: "Русский",
  },
  {
    value: "rw",
    label: "Rwandi",
    native: "Kinyarwandi",
  },
  {
    value: "sa",
    label: "Sanskrit",
    native: "संस्कृतम्",
  },
  {
    value: "sc",
    label: "Sardinian",
    native: "Sardu",
  },
  {
    value: "sd",
    label: "Sindhi",
    native: "सिनधि",
  },
  {
    value: "se",
    label: "Northern Sami",
    native: "Sámegiella",
  },
  {
    value: "sg",
    label: "Sango",
    native: "Sängö",
  },
  {
    value: "sh",
    label: "Serbo-Croatian",
    native: "Srpskohrvatski / Српскохрватски",
  },
  {
    value: "si",
    label: "Sinhalese",
    native: "සිංහල",
  },
  {
    value: "sk",
    label: "Slovak",
    native: "Slovenčina",
  },
  {
    value: "sl",
    label: "Slovenian",
    native: "Slovenščina",
  },
  {
    value: "sm",
    label: "Samoan",
    native: "Gagana Samoa",
  },
  {
    value: "sn",
    label: "Shona",
    native: "chiShona",
  },
  {
    value: "so",
    label: "Somalia",
    native: "Soomaaliga",
  },
  {
    value: "sq",
    label: "Albanian",
    native: "Shqip",
  },
  {
    value: "sr",
    label: "Serbian",
    native: "Српски",
  },
  {
    value: "ss",
    label: "Swati",
    native: "SiSwati",
  },
  {
    value: "st",
    label: "Southern Sotho",
    native: "Sesotho",
  },
  {
    value: "su",
    label: "Sundanese",
    native: "Basa Sunda",
  },
  {
    value: "sv",
    label: "Swedish",
    native: "Svenska",
  },
  {
    value: "sw",
    label: "Swahili",
    native: "Kiswahili",
  },
  {
    value: "ta",
    label: "Tamil",
    native: "தமிழ்",
  },
  {
    value: "te",
    label: "Telugu",
    native: "తెలుగు",
  },
  {
    value: "tg",
    label: "Tajik",
    native: "Тоҷикӣ",
  },
  {
    value: "th",
    label: "Thai",
    native: "ไทย / Phasa Thai",
  },
  {
    value: "ti",
    label: "Tigrinya",
    native: "ትግርኛ",
  },
  {
    value: "tk",
    label: "Turkmen",
    native: "Туркмен / تركمن",
  },
  {
    value: "tl",
    label: "Tagalog / Filipino",
    native: "Tagalog",
  },
  {
    value: "tn",
    label: "Tswana",
    native: "Setswana",
  },
  {
    value: "to",
    label: "Tonga",
    native: "Lea Faka-Tonga",
  },
  {
    value: "tr",
    label: "Turkish",
    native: "Türkçe",
  },
  {
    value: "ts",
    label: "Tsonga",
    native: "Xitsonga",
  },
  {
    value: "tt",
    label: "Tatar",
    native: "Tatarça",
  },
  {
    value: "tw",
    label: "Twi",
    native: "Twi",
  },
  {
    value: "ty",
    label: "Tahitian",
    native: "Reo Mā`ohi",
  },
  {
    value: "ug",
    label: "Uyghur",
    native: "Uyƣurqə / ئۇيغۇرچە",
  },
  {
    value: "uk",
    label: "Ukrainian",
    native: "Українська",
  },
  {
    value: "ur",
    label: "Urdu",
    native: "اردو",
  },
  {
    value: "uz",
    label: "Uzbek",
    native: "Ўзбек",
  },
  {
    value: "ve",
    label: "Venda",
    native: "Tshivenḓa",
  },
  {
    value: "vi",
    label: "Vietnamese",
    native: "Tiếng Việt",
  },
  {
    value: "vo",
    label: "Volapük",
    native: "Volapük",
  },
  {
    value: "wa",
    label: "Walloon",
    native: "Walon",
  },
  {
    value: "wo",
    label: "Wolof",
    native: "Wollof",
  },
  {
    value: "xh",
    label: "Xhosa",
    native: "isiXhosa",
  },
  {
    value: "yi",
    label: "Yiddish",
    native: "ייִדיש",
  },
  {
    value: "yo",
    label: "Yoruba",
    native: "Yorùbá",
  },
  {
    value: "za",
    label: "Zhuang",
    native: "Cuengh / Tôô / 壮语",
  },
  {
    value: "zh",
    label: "Chinese",
    native: "中文",
  },
  {
    value: "zu",
    label: "Zulu",
    native: "isiZulu",
  },
];

// 🖼️ Media types
const mediaTypes: FilterOption[] = [
  { value: "IMAGE", label: "Images", icon: ImageIcon },
  { value: "MEME", label: "Memes", icon: Laugh },
  { value: "IMAGE_AND_MEME", label: "Images and memes", icon: Images },
  { value: "VIDEO", label: "Videos", icon: Video },
  { value: "NONE", label: "No image or video", icon: Ban },
];

// 📱 Platforms
const platforms: FilterOption[] = [
  { value: "FACEBOOK", label: "Facebook", icon: Facebook },
  { value: "INSTAGRAM", label: "Instagram", icon: Instagram },
  { value: "AUDIENCE_NETWORK", label: "Audience Network", icon: Users },
  { value: "MESSENGER", label: "Messenger", icon: MessageCircle },
];

// 🔄 Status options
const statuses: FilterOption[] = [
  { value: "ALL", label: "Active and Inactive", icon: CircleDot },
  { value: "ACTIVE", label: "Active", icon: CircleCheckBig },
  { value: "INACTIVE", label: "Inactive", icon: CircleSlash2 },
];

// 🧩 Filter configuration
export const filterConfig: FilterConfig[] = [
  {
    key: "searchType",
    paramKey: "search_type",
    label: "Keyword",
    icon: "/filters/key.svg",
    options: searchTypes,
  },
  {
    key: "category",
    paramKey: "ad_type",
    label: "Type",
    icon: "/filters/search-demography.svg",
    options: categories,
  },
  {
    key: "country",
    paramKey: "countries",
    label: "Country",
    icon: "/filters/location.svg",
    multiSelect: true,
    options: countryCodesAlpha2Flag,
  },
  {
    key: "categoryAsKeyword",
    paramKey: "category_as_keyword",
    label: "Category",
    icon: "/filters/category.svg",
    options: categoryKeywords,
  },
  {
    key: "language",
    paramKey: "content_languages",
    label: "Language",
    icon: "/filters/translate.svg",
    multiSelect: true,
    options: languages,
  },
  {
    key: "media",
    paramKey: "media_type",
    label: "Media",
    icon: "/filters/gallery.svg",
    options: mediaTypes,
  },
  {
    key: "platform",
    paramKey: "publisher_platforms",
    label: "Platform",
    icon: "/filters/fb.svg",
    multiSelect: true,
    options: platforms,
  },
  {
    key: "status",
    paramKey: "active_status",
    label: "Status",
    icon: "/filters/active.svg",
    options: statuses,
  },
  {
    key: "startDate",
    paramKey: "start_date",
    label: "Start Date",
    icon: "/filters/clock-on.svg",
  },
  {
    key: "endDate",
    paramKey: "end_date",
    label: "End Date",
    icon: "/filters/clock-off.svg",
  },
];
